# Generated by Django 5.2.9 on 2025-12-24 14:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_add_zone_slot_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryDriver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "driver_type",
                    models.CharField(
                        choices=[
                            ("employee", "Clinic Employee"),
                            ("contractor", "Independent Contractor"),
                        ],
                        default="employee",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "rfc",
                    models.CharField(
                        blank=True, help_text="RFC (Tax ID)", max_length=13
                    ),
                ),
                (
                    "curp",
                    models.CharField(
                        blank=True, help_text="CURP (Personal ID)", max_length=18
                    ),
                ),
                (
                    "rate_per_delivery",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "rate_per_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("contract_signed", models.BooleanField(default=False)),
                (
                    "contract_document",
                    models.FileField(
                        blank=True, null=True, upload_to="driver_contracts/"
                    ),
                ),
                (
                    "id_document",
                    models.FileField(blank=True, null=True, upload_to="driver_ids/"),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("motorcycle", "Motorcycle"),
                            ("car", "Car"),
                            ("bicycle", "Bicycle"),
                            ("walk", "On Foot"),
                        ],
                        default="motorcycle",
                        max_length=20,
                    ),
                ),
                ("license_plate", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("is_available", models.BooleanField(default=False)),
                ("total_deliveries", models.PositiveIntegerField(default=0)),
                ("successful_deliveries", models.PositiveIntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.00"), max_digits=3
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_driver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zones",
                    models.ManyToManyField(
                        blank=True, related_name="drivers", to="delivery.deliveryzone"
                    ),
                ),
            ],
            options={
                "ordering": ["-is_available", "user__first_name"],
            },
        ),
    ]
