# Generated by Django 5.2.9 on 2025-12-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0004_add_proof_rating_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverydriver",
            name="current_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="deliverydriver",
            name="current_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="deliverydriver",
            name="location_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
