# Generated by Django 5.2.9 on 2025-12-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0005_add_driver_location_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverydriver",
            name="max_deliveries_per_day",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Maximum deliveries this driver can handle per day",
            ),
        ),
    ]
