# Generated by Django 5.2.9 on 2025-12-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0006_add_max_deliveries_per_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverydriver",
            name="onboarding_notes",
            field=models.TextField(
                blank=True, help_text="Admin notes about onboarding"
            ),
        ),
        migrations.AddField(
            model_name="deliverydriver",
            name="onboarding_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("documents_submitted", "Documents Submitted"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="Contractor onboarding status",
                max_length=20,
            ),
        ),
    ]
