# Generated by Django 5.2.9 on 2025-12-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0007_add_onboarding_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="delivered_distance_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Actual distance traveled in kilometers",
                max_digits=10,
                null=True,
            ),
        ),
    ]
