# Generated by Django 5.2.9 on 2025-12-26 02:50

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0008_add_delivered_distance_km"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverydriver",
            name="contract_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.core.storage.delivery_contract_path,
            ),
        ),
        migrations.AlterField(
            model_name="deliverydriver",
            name="id_document",
            field=models.FileField(
                blank=True, null=True, upload_to=apps.core.storage.delivery_id_path
            ),
        ),
        migrations.AlterField(
            model_name="deliveryproof",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.core.storage.delivery_proof_path
            ),
        ),
    ]
