# Generated by Django 5.2.9 on 2025-12-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0009_alter_deliverydriver_contract_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverydriver",
            name="is_manager",
            field=models.BooleanField(
                default=False,
                help_text="Managers can view all deliveries, not just their own",
            ),
        ),
    ]
