# Generated by Django 5.2.9 on 2025-12-27 08:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0010_add_is_manager_to_driver"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliverydriver",
            options={
                "ordering": ["-is_available", "user__first_name"],
                "verbose_name": "delivery driver (deprecated)",
                "verbose_name_plural": "delivery drivers (deprecated)",
            },
        ),
        migrations.CreateModel(
            name="DriverCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("motorcycle", "Motorcycle"),
                            ("car", "Car"),
                            ("bicycle", "Bicycle"),
                            ("walk", "On Foot"),
                        ],
                        default="motorcycle",
                        max_length=20,
                    ),
                ),
                ("license_plate", models.CharField(blank=True, max_length=20)),
                ("drivers_license_number", models.CharField(blank=True, max_length=50)),
                ("drivers_license_expiry", models.DateField(blank=True, null=True)),
                (
                    "rate_per_delivery",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rate paid per delivery (for contractors)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "rate_per_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rate paid per kilometer (for contractors)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_available",
                    models.BooleanField(
                        default=False, help_text="Currently available for deliveries"
                    ),
                ),
                (
                    "is_manager",
                    models.BooleanField(
                        default=False,
                        help_text="Managers can view all deliveries, not just their own",
                    ),
                ),
                (
                    "max_deliveries_per_day",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Maximum deliveries this driver can handle per day",
                    ),
                ),
                (
                    "current_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "current_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("location_updated_at", models.DateTimeField(blank=True, null=True)),
                ("total_deliveries", models.PositiveIntegerField(default=0)),
                ("successful_deliveries", models.PositiveIntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.00"), max_digits=3
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_capability",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="person",
                    ),
                ),
                (
                    "zones",
                    models.ManyToManyField(
                        blank=True,
                        related_name="capable_drivers",
                        to="delivery.deliveryzone",
                    ),
                ),
            ],
            options={
                "verbose_name": "driver capability",
                "verbose_name_plural": "driver capabilities",
                "ordering": ["-is_available", "person__first_name"],
            },
        ),
    ]
