# Generated by Django 5.2.9 on 2025-12-24 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("pets", "0004_alter_medication_prescribing_vet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("oncology", "Oncology"),
                            ("cardiology", "Cardiology"),
                            ("orthopedics", "Orthopedics"),
                            ("ophthalmology", "Ophthalmology"),
                            ("dermatology", "Dermatology"),
                            ("neurology", "Neurology"),
                            ("surgery", "Surgery"),
                            ("internal_medicine", "Internal Medicine"),
                            ("emergency", "Emergency/Critical Care"),
                            ("imaging", "Imaging/Radiology"),
                            ("laboratory", "Laboratory"),
                            ("rehabilitation", "Rehabilitation"),
                            ("behavior", "Behavior"),
                            ("exotics", "Exotic Animals"),
                            ("dentistry", "Dentistry"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("credentials", models.CharField(blank=True, max_length=200)),
                ("is_facility", models.BooleanField(default=False)),
                ("clinic_name", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("fax", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("distance_km", models.FloatField(blank=True, null=True)),
                ("is_24_hours", models.BooleanField(default=False)),
                ("hours", models.JSONField(default=dict)),
                ("services", models.JSONField(default=list)),
                ("species_treated", models.JSONField(default=list)),
                ("is_visiting", models.BooleanField(default=False)),
                ("visiting_services", models.JSONField(default=list)),
                ("equipment_provided", models.JSONField(default=list)),
                (
                    "relationship_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("referral_agreement", models.TextField(blank=True)),
                (
                    "revenue_share_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("total_referrals_sent", models.IntegerField(default=0)),
                ("total_referrals_received", models.IntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("referral_instructions", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("outbound", "Outbound (To Specialist)"),
                            ("inbound", "Inbound (From Other Vet)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "referral_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("referring_vet_name", models.CharField(blank=True, max_length=200)),
                ("referring_clinic", models.CharField(blank=True, max_length=200)),
                ("referring_contact", models.CharField(blank=True, max_length=200)),
                ("reason", models.TextField()),
                ("clinical_summary", models.TextField(blank=True)),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("routine", "Routine"),
                            ("urgent", "Urgent (Within Week)"),
                            ("emergency", "Emergency (Same Day)"),
                        ],
                        default="routine",
                        max_length=20,
                    ),
                ),
                ("requested_services", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("received", "Received by Specialist"),
                            ("scheduled", "Appointment Scheduled"),
                            ("seen", "Patient Seen"),
                            ("report_pending", "Awaiting Report"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("declined", "Declined by Specialist"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("appointment_date", models.DateTimeField(blank=True, null=True)),
                ("seen_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("specialist_findings", models.TextField(blank=True)),
                ("specialist_diagnosis", models.TextField(blank=True)),
                ("specialist_recommendations", models.TextField(blank=True)),
                ("follow_up_needed", models.BooleanField(default=False)),
                ("follow_up_instructions", models.TextField(blank=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("successful", "Successful Treatment"),
                            ("ongoing", "Ongoing Treatment"),
                            ("referred_again", "Referred to Another Specialist"),
                            ("no_treatment", "No Treatment Possible"),
                            ("client_declined", "Client Declined Treatment"),
                            ("euthanasia", "Euthanasia"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("outcome_notes", models.TextField(blank=True)),
                ("client_satisfaction", models.IntegerField(blank=True, null=True)),
                ("quality_rating", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.invoice",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pet_referrals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialist_referrals",
                        to="pets.pet",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referring_professional_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.professionalaccount",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals_received",
                        to="referrals.specialist",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferralDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("referral_letter", "Referral Letter"),
                            ("medical_history", "Medical History"),
                            ("lab_results", "Lab Results"),
                            ("imaging", "Imaging (X-ray, Ultrasound)"),
                            ("specialist_report", "Specialist Report"),
                            ("prescription", "Prescription"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="referrals/")),
                ("description", models.TextField(blank=True)),
                ("is_outgoing", models.BooleanField(default=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "referral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="referrals.referral",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReferralNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("is_internal", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_list",
                        to="referrals.referral",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VisitingSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_recurring", models.BooleanField(default=False)),
                ("recurrence_pattern", models.CharField(blank=True, max_length=50)),
                ("max_appointments", models.IntegerField(blank=True, null=True)),
                ("appointments_booked", models.IntegerField(default=0)),
                ("services_available", models.JSONField(default=list)),
                ("equipment_bringing", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("cancellation_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visiting_schedules",
                        to="referrals.specialist",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="VisitingAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_time", models.TimeField()),
                ("duration_minutes", models.IntegerField(default=30)),
                ("service", models.CharField(max_length=100)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("findings", models.TextField(blank=True)),
                ("diagnosis", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                (
                    "report_file",
                    models.FileField(
                        blank=True, null=True, upload_to="visiting_reports/"
                    ),
                ),
                ("images", models.JSONField(default=list)),
                (
                    "fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "pet_friendly_share",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("follow_up_needed", models.BooleanField(default=False)),
                ("follow_up_notes", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.invoice",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visiting_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visiting_appointments",
                        to="pets.pet",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="referrals.referral",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="referrals.specialist",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="referrals.visitingschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["schedule__date", "appointment_time"],
            },
        ),
    ]
