# Generated by Django 5.2.9 on 2025-12-26 02:50

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referraldocument",
            name="file",
            field=models.FileField(upload_to=apps.core.storage.referral_file_path),
        ),
        migrations.AlterField(
            model_name="visitingappointment",
            name="report_file",
            field=models.FileField(
                blank=True, null=True, upload_to=apps.core.storage.visiting_report_path
            ),
        ),
    ]
