# Generated by Django 5.2.9 on 2025-12-24 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0002_reminder_fields"),
        ("pets", "0004_alter_medication_prescribing_vet"),
        ("practice", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyReferral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=11)),
                ("distance_km", models.FloatField(blank=True, null=True)),
                ("is_24_hours", models.BooleanField(default=False)),
                ("hours", models.JSONField(default=dict)),
                ("services", models.JSONField(default=list)),
                ("species_treated", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("last_verified", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["distance_km", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmergencySymptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=100)),
                ("keywords_es", models.JSONField(default=list)),
                ("keywords_en", models.JSONField(default=list)),
                ("species", models.JSONField(default=list)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical - Life Threatening"),
                            ("urgent", "Urgent - Needs Same-Day Care"),
                            ("moderate", "Moderate - Can Wait"),
                            ("low", "Low - Schedule Appointment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("follow_up_questions", models.JSONField(default=list)),
                ("first_aid_instructions", models.TextField(blank=True)),
                ("warning_signs", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["severity", "keyword"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("web", "Website"),
                            ("whatsapp", "WhatsApp"),
                            ("phone", "Phone"),
                            ("sms", "SMS"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reported_symptoms", models.TextField()),
                ("pet_species", models.CharField(max_length=50)),
                ("pet_age", models.CharField(blank=True, max_length=50)),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("critical", "Critical - Life Threatening"),
                            ("urgent", "Urgent - Needs Same-Day Care"),
                            ("moderate", "Moderate - Can Wait"),
                            ("low", "Low - Schedule Appointment"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("triage_notes", models.TextField(blank=True)),
                ("ai_assessment", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("triaging", "Triaging"),
                            ("escalated", "Escalated to Staff"),
                            ("resolved", "Resolved"),
                            ("referred", "Referred Elsewhere"),
                            ("no_response", "No Response"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("response_time_seconds", models.IntegerField(blank=True, null=True)),
                ("resolution", models.TextField(blank=True)),
                ("outcome", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_contacts",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_contacts_handled",
                        to="practice.staffprofile",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_contacts",
                        to="pets.pet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyFirstAid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_es", models.CharField(max_length=200)),
                ("condition", models.CharField(max_length=100)),
                ("species", models.JSONField(default=list)),
                ("description", models.TextField()),
                ("description_es", models.TextField()),
                ("steps", models.JSONField(default=list)),
                ("warnings", models.JSONField(default=list)),
                ("do_not", models.JSONField(default=list)),
                ("video_url", models.URLField(blank=True)),
                ("images", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_symptoms",
                    models.ManyToManyField(
                        blank=True,
                        related_name="first_aid_guides",
                        to="emergency.emergencysymptom",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Emergency First Aid",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="OnCallSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("contact_phone", models.CharField(max_length=20)),
                ("backup_phone", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("swap_requested", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oncall_schedules",
                        to="practice.staffprofile",
                    ),
                ),
                (
                    "swap_with",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="swap_requests",
                        to="practice.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
                "unique_together": {("staff", "date")},
            },
        ),
    ]
