# Generated by Django 5.2.9 on 2025-12-26 02:50

import apps.accounts.validators
import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.core.storage.avatar_path,
                validators=[
                    apps.accounts.validators.validate_file_size,
                    apps.accounts.validators.validate_image_type,
                ],
                verbose_name="avatar",
            ),
        ),
    ]
