# Generated by Django 5.2.9 on 2025-12-26 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_email",
                    models.EmailField(max_length=254, verbose_name="new email address"),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="verification token"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "old_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="old email address"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "email change request",
                "verbose_name_plural": "email change requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
