# Generated by Django 5.2.9 on 2025-12-27 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_create_module_permissions"),
        ("parties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="person",
            field=models.ForeignKey(
                blank=True,
                help_text="The real-world person this account belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts",
                to="parties.person",
                verbose_name="person",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="auth_method",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("google", "Google"),
                    ("apple", "Apple"),
                    ("facebook", "Facebook"),
                    ("api_key", "API Key"),
                ],
                default="email",
                max_length=20,
                verbose_name="authentication method",
            ),
        ),
    ]
