# Generated by Django 5.2.9 on 2025-12-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Credit/Debit Card"),
                    ("transfer", "Bank Transfer"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
