# Generated by Django 5.2.9 on 2025-12-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_add_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_order_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum quantity per order. Leave blank to use default from settings.', null=True),
        ),
    ]
