# Generated by Django 5.2.9 on 2025-12-24 13:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_add_max_order_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        help_text="Default shipping cost for delivery orders",
                        max_digits=10,
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Order subtotal for free shipping. Leave blank to disable.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.16"),
                        help_text="Tax rate as decimal (e.g., 0.16 for 16%)",
                        max_digits=4,
                    ),
                ),
                (
                    "default_max_order_quantity",
                    models.PositiveIntegerField(
                        default=99, help_text="Default max items per product per order"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Store Settings",
                "verbose_name_plural": "Store Settings",
            },
        ),
    ]
