# Generated by Django 5.2.9 on 2025-12-26 02:50

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_add_store_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.core.storage.category_image_path
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to=apps.core.storage.product_image_path),
        ),
    ]
