# Generated by Django 5.2.9 on 2025-12-26 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_add_tax_and_sat_models"),
        ("inventory", "0003_add_inventory_item_model"),
        ("store", "0005_alter_category_image_alter_productimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="inventory_item",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to central inventory item for SAT compliance",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="store_product",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tax_rate_override",
            field=models.ForeignKey(
                blank=True,
                help_text="Override the default tax rate for this product",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products_override",
                to="billing.taxrate",
            ),
        ),
    ]
