# Generated by Django 5.2.9 on 2025-12-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_add_inventory_item_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique identifier (e.g., 'physical', 'service')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_es", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "requires_inventory",
                    models.BooleanField(
                        default=False,
                        help_text="Products of this type need inventory tracking",
                    ),
                ),
                (
                    "requires_service_module",
                    models.BooleanField(
                        default=False,
                        help_text="Products of this type link to service/procedure records",
                    ),
                ),
                (
                    "allows_shipping",
                    models.BooleanField(
                        default=True, help_text="Products of this type can be shipped"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product Type",
                "verbose_name_plural": "Product Types",
                "ordering": ["name"],
            },
        ),
    ]
