# Generated by Django 5.2.9 on 2025-12-26 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_producttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Product type (physical, service, bundle, etc.)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="store.producttype",
            ),
        ),
    ]
