# Generated by Django 5.2.9 on 2025-12-26 02:50

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="cfdi_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to=apps.core.storage.cfdi_path
            ),
        ),
        migrations.AlterField(
            model_name="professionalstatement",
            name="pdf",
            field=models.FileField(
                blank=True, null=True, upload_to=apps.core.storage.statement_path
            ),
        ),
    ]
