# Generated by Django 5.2.9 on 2025-12-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_alter_invoice_cfdi_pdf_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SATProductCode",
            fields=[
                (
                    "code",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=500)),
                ("includes_iva", models.BooleanField(default=False)),
                ("iva_exempt", models.BooleanField(default=False)),
                ("iva_zero_rate", models.BooleanField(default=False)),
                ("ieps_applicable", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "SAT Product Code",
                "verbose_name_plural": "SAT Product Codes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="SATUnitCode",
            fields=[
                (
                    "code",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "SAT Unit Code",
                "verbose_name_plural": "SAT Unit Codes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("iva", "IVA (Value Added Tax)"),
                            ("ieps", "IEPS (Special Products Tax)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=4, max_digits=6)),
                ("sat_impuesto_code", models.CharField(max_length=3)),
                ("sat_tipo_factor", models.CharField(default="Tasa", max_length=10)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["tax_type", "-rate"],
            },
        ),
    ]
