# Generated by Django 5.2.9 on 2025-12-23 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0003_vaccination_reminder_sent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="business name"),
                ),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("grooming", "Grooming"),
                            ("boarding", "Boarding"),
                            ("training", "Training"),
                            ("daycare", "Daycare"),
                            ("pet_sitting", "Pet Sitting"),
                            ("transport", "Pet Transport"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="contact name"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="phone"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                ("address", models.TextField(blank=True, verbose_name="address")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "services_offered",
                    models.TextField(blank=True, verbose_name="services offered"),
                ),
                (
                    "hours_of_operation",
                    models.TextField(blank=True, verbose_name="hours of operation"),
                ),
                (
                    "price_range",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="price range"
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="average rating",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_preferred",
                    models.BooleanField(
                        default=False, verbose_name="preferred partner"
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="internal notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "external partner",
                "verbose_name_plural": "external partners",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("grooming", "Grooming"),
                            ("boarding", "Boarding"),
                            ("training", "Training"),
                            ("daycare", "Daycare"),
                            ("pet_sitting", "Pet Sitting"),
                            ("transport", "Pet Transport"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="service type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("contacted", "Contacted"),
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "preferred_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="preferred date"
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="scheduled date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("feedback", models.TextField(blank=True, verbose_name="feedback")),
                (
                    "rating",
                    models.IntegerField(blank=True, null=True, verbose_name="rating"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="services.externalpartner",
                        verbose_name="partner",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="pets.pet",
                        verbose_name="pet",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="referred by",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral",
                "verbose_name_plural": "referrals",
                "ordering": ["-created_at"],
            },
        ),
    ]
