# Generated by Django 5.2.9 on 2025-12-24 00:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "name_es",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="name (Spanish)"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("consultation", "Consultation"),
                            ("vaccination", "Vaccination"),
                            ("surgery", "Surgery"),
                            ("dental", "Dental"),
                            ("laboratory", "Laboratory"),
                            ("imaging", "Imaging"),
                            ("grooming", "Grooming"),
                            ("emergency", "Emergency"),
                            ("preventive", "Preventive Care"),
                            ("other", "Other"),
                        ],
                        default="consultation",
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="base price",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=30, verbose_name="duration (minutes)"
                    ),
                ),
                (
                    "clave_producto_sat",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="SAT product code"
                    ),
                ),
                (
                    "clave_unidad_sat",
                    models.CharField(
                        default="E48", max_length=5, verbose_name="SAT unit code"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "requires_appointment",
                    models.BooleanField(
                        default=True, verbose_name="requires appointment"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "service",
                "verbose_name_plural": "services",
                "ordering": ["category", "name"],
            },
        ),
    ]
