# Generated by Django 5.2.9 on 2025-12-27 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0002_reminder_fields"),
        ("billing", "0003_add_tax_and_sat_models"),
        ("locations", "0001_initial"),
        ("practice", "0008_add_emr_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pipeline_state",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("checked_in", "Checked In"),
                            ("roomed", "Roomed"),
                            ("in_exam", "In Exam"),
                            ("pending_orders", "Pending Orders"),
                            ("awaiting_results", "Awaiting Results"),
                            ("treatment", "Treatment"),
                            ("checkout", "Checkout"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=20,
                        verbose_name="pipeline state",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="scheduled at"
                    ),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="checked in at"
                    ),
                ),
                (
                    "roomed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="roomed at"
                    ),
                ),
                (
                    "exam_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="exam started at"
                    ),
                ),
                (
                    "exam_ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="exam ended at"
                    ),
                ),
                (
                    "discharged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="discharged at"
                    ),
                ),
                (
                    "room",
                    models.CharField(
                        blank=True,
                        help_text="Exam room or treatment area",
                        max_length=50,
                        verbose_name="room",
                    ),
                ),
                (
                    "encounter_type",
                    models.CharField(
                        choices=[
                            ("routine", "Routine/Wellness"),
                            ("urgent", "Urgent Care"),
                            ("emergency", "Emergency"),
                            ("follow_up", "Follow-up"),
                            ("telehealth", "Telehealth"),
                            ("surgery", "Surgery"),
                            ("dental", "Dental"),
                            ("grooming", "Grooming"),
                            ("boarding", "Boarding"),
                            ("other", "Other"),
                        ],
                        default="routine",
                        max_length=20,
                        verbose_name="encounter type",
                    ),
                ),
                (
                    "chief_complaint",
                    models.TextField(
                        blank=True,
                        help_text="Primary reason for visit",
                        verbose_name="chief complaint",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounter",
                        to="appointments.appointment",
                        verbose_name="appointment",
                    ),
                ),
                (
                    "assigned_tech",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounters_as_tech",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned technician",
                    ),
                ),
                (
                    "assigned_vet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounters_as_vet",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned veterinarian",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounters_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounters",
                        to="billing.invoice",
                        verbose_name="invoice",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Facility/site where this encounter occurs",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encounters",
                        to="locations.location",
                        verbose_name="location",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to="practice.patientrecord",
                        verbose_name="patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "encounter",
                "verbose_name_plural": "encounters",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problem_type",
                    models.CharField(
                        choices=[
                            ("diagnosis", "Diagnosis"),
                            ("allergy", "Allergy"),
                            ("chronic", "Chronic Condition"),
                            ("behavioral", "Behavioral"),
                            ("other", "Other"),
                        ],
                        default="diagnosis",
                        max_length=20,
                        verbose_name="problem type",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="moderate",
                        max_length=20,
                        verbose_name="severity",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g., "Diabetes Mellitus Type II", "Penicillin Allergy"',
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "onset_date",
                    models.DateField(
                        blank=True,
                        help_text="When the problem was first identified",
                        null=True,
                        verbose_name="onset date",
                    ),
                ),
                (
                    "resolved_date",
                    models.DateField(
                        blank=True,
                        help_text="When the problem was resolved (if applicable)",
                        null=True,
                        verbose_name="resolved date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("controlled", "Controlled"),
                            ("resolved", "Resolved"),
                            ("inactive", "Inactive"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "is_alert",
                    models.BooleanField(
                        default=False,
                        help_text="Display prominently in patient header",
                        verbose_name="show as alert",
                    ),
                ),
                (
                    "alert_text",
                    models.CharField(
                        blank=True,
                        help_text='Short text for alert banner, e.g., "ALLERGIC TO PENICILLIN"',
                        max_length=100,
                        verbose_name="alert text",
                    ),
                ),
                (
                    "alert_severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("danger", "Danger"),
                        ],
                        default="warning",
                        max_length=10,
                        verbose_name="alert severity",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="problems_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="practice.patientrecord",
                        verbose_name="patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "patient problem",
                "verbose_name_plural": "patient problems",
                "ordering": ["-is_alert", "-severity", "name"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("encounter_created", "Encounter Created"),
                            ("state_change", "Pipeline State Change"),
                            ("problem_added", "Problem Added"),
                            ("problem_resolved", "Problem Resolved"),
                            ("note", "Clinical Note"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="event type",
                    ),
                ),
                (
                    "event_subtype",
                    models.CharField(
                        blank=True,
                        help_text="Additional classification (e.g., state transition name)",
                        max_length=50,
                        verbose_name="event subtype",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the clinical event occurred",
                        verbose_name="occurred at",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the event was recorded in system",
                        verbose_name="recorded at",
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        help_text="Human-readable summary for timeline display",
                        max_length=500,
                        verbose_name="summary",
                    ),
                ),
                (
                    "is_significant",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as significant for filtering important events",
                        verbose_name="significant",
                    ),
                ),
                (
                    "is_entered_in_error",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as entered in error (original stays, this flags it)",
                        verbose_name="entered in error",
                    ),
                ),
                (
                    "error_corrected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="error corrected at"
                    ),
                ),
                (
                    "error_correction_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for marking as entered in error",
                        verbose_name="correction reason",
                    ),
                ),
                (
                    "error_corrected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emr_corrections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="error corrected by",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Where this event was recorded (auto-set from encounter if present)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_events",
                        to="locations.location",
                        verbose_name="location",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_events",
                        to="practice.patientrecord",
                        verbose_name="patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinical_events_recorded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recorded by",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to corrected version of this event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="emr.clinicalevent",
                        verbose_name="superseded by",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Encounter this event occurred during (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_events",
                        to="emr.encounter",
                        verbose_name="encounter",
                    ),
                ),
                (
                    "patient_problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_events",
                        to="emr.patientproblem",
                        verbose_name="patient problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "clinical event",
                "verbose_name_plural": "clinical events",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["location", "-created_at"],
                name="emr_encount_locatio_94885e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["location", "pipeline_state"],
                name="emr_encount_locatio_2ca57f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["patient", "-created_at"], name="emr_encount_patient_4716c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientproblem",
            index=models.Index(
                fields=["patient", "status"], name="emr_patient_patient_bc56ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientproblem",
            index=models.Index(
                fields=["is_alert"], name="emr_patient_is_aler_27f5e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalevent",
            index=models.Index(
                fields=["patient", "-occurred_at"],
                name="emr_clinica_patient_ee271e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalevent",
            index=models.Index(
                fields=["encounter", "-occurred_at"],
                name="emr_clinica_encount_d910f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalevent",
            index=models.Index(
                fields=["location", "-occurred_at"],
                name="emr_clinica_locatio_c95ea7_idx",
            ),
        ),
    ]
