# Generated by Django 5.2.9 on 2025-12-27 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0001_initial"),
        ("locations", "0002_add_exam_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="exam_room",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned exam room from location",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="encounters",
                to="locations.examroom",
                verbose_name="exam room",
            ),
        ),
        migrations.AlterField(
            model_name="encounter",
            name="room",
            field=models.CharField(
                blank=True,
                help_text="LEGACY: Use exam_room FK instead",
                max_length=50,
                verbose_name="room",
            ),
        ),
    ]
