# Generated by Django 5.2.9 on 2025-12-24 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltyProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "points_per_currency",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Points earned per currency unit spent",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("min_points", models.IntegerField(default=0)),
                ("max_points", models.IntegerField(blank=True, null=True)),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "points_multiplier",
                    models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
                ),
                ("benefits", models.JSONField(blank=True, default=list)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="loyalty.loyaltyprogram",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "min_points"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("discount", "Discount"),
                            ("free_service", "Free Service"),
                            ("free_product", "Free Product"),
                            ("voucher", "Voucher"),
                            ("special", "Special Reward"),
                        ],
                        max_length=20,
                    ),
                ),
                ("points_cost", models.IntegerField()),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("quantity_available", models.IntegerField(blank=True, null=True)),
                ("quantity_redeemed", models.IntegerField(default=0)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to="loyalty.loyaltyprogram",
                    ),
                ),
                (
                    "min_tier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Minimum tier required to redeem",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="loyalty.loyaltytier",
                    ),
                ),
            ],
            options={
                "ordering": ["points_cost"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_balance", models.IntegerField(default=0)),
                ("lifetime_points", models.IntegerField(default=0)),
                ("points_redeemed", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="loyalty.loyaltyprogram",
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounts",
                        to="loyalty.loyaltytier",
                    ),
                ),
            ],
            options={
                "ordering": ["-lifetime_points"],
            },
        ),
        migrations.CreateModel(
            name="PointTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earn", "Earned"),
                            ("redeem", "Redeemed"),
                            ("bonus", "Bonus"),
                            ("adjustment", "Adjustment"),
                            ("expire", "Expired"),
                            ("referral", "Referral Bonus"),
                        ],
                        max_length=20,
                    ),
                ),
                ("points", models.IntegerField()),
                ("balance_after", models.IntegerField()),
                ("description", models.CharField(max_length=200)),
                ("reference_type", models.CharField(blank=True, max_length=50)),
                ("reference_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="loyalty.loyaltyaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referred_email", models.EmailField(max_length=254)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("referrer_points_awarded", models.IntegerField(default=0)),
                ("referred_points_awarded", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "referred",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_referrals_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_referrals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferralProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referrer_bonus",
                    models.IntegerField(
                        default=100,
                        help_text="Points for referrer when referred user makes first purchase",
                    ),
                ),
                (
                    "referred_bonus",
                    models.IntegerField(
                        default=50,
                        help_text="Points for referred user on first purchase",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "program",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_program",
                        to="loyalty.loyaltyprogram",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RewardRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_spent", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=50, unique=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="loyalty.loyaltyaccount",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="loyalty.loyaltyreward",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
