# Generated by Django 5.2.9 on 2025-12-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("question", "General Question"),
                            ("appointment", "Appointment Request"),
                            ("emergency", "Emergency"),
                            ("pricing", "Pricing Information"),
                            ("feedback", "Feedback"),
                            ("other", "Other"),
                        ],
                        default="question",
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("responded", "Responded"),
                            ("archived", "Archived"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("response_notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Contact Submission",
                "verbose_name_plural": "Contact Submissions",
                "ordering": ["-created_at"],
            },
        ),
    ]
