# Generated by Django 5.2.9 on 2025-12-26 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_contact_submission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "app_name",
                    models.CharField(
                        help_text='Django app name (e.g., "appointments")',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name for the module", max_length=100
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("operations", "Operations"),
                            ("customers", "Customers"),
                            ("finance", "Finance"),
                            ("admin", "Admin"),
                            ("system", "System"),
                        ],
                        default="operations",
                        help_text="Navigation section this module belongs to",
                        max_length=50,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Whether this module is active"
                    ),
                ),
                (
                    "disabled_at",
                    models.DateTimeField(
                        blank=True, help_text="When the module was disabled", null=True
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text='Icon name for navigation (e.g., "calendar")',
                        max_length=50,
                    ),
                ),
                (
                    "url_name",
                    models.CharField(
                        blank=True,
                        help_text='URL pattern name (e.g., "appointments:list")',
                        max_length=100,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in navigation menu"
                    ),
                ),
                (
                    "disabled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who disabled this module",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disabled_modules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Module Configuration",
                "verbose_name_plural": "Module Configurations",
                "ordering": ["section", "sort_order", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        help_text='Unique identifier (e.g., "appointments.online_booking")',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="What this feature flag controls"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Whether this feature is active"
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent module (null for global flags)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_flags",
                        to="core.moduleconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Flag",
                "verbose_name_plural": "Feature Flags",
                "ordering": ["key"],
            },
        ),
    ]
