# Generated by Django 5.2.9 on 2025-12-22 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "name_es",
                    models.CharField(max_length=100, verbose_name="name (Spanish)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="name (English)"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="icon"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="order")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="knowledge.knowledgecategory",
                        verbose_name="parent category",
                    ),
                ),
            ],
            options={
                "verbose_name": "knowledge category",
                "verbose_name_plural": "knowledge categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "title_es",
                    models.CharField(max_length=255, verbose_name="title (Spanish)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=255, verbose_name="title (English)"),
                ),
                ("content", models.TextField(verbose_name="content")),
                ("content_es", models.TextField(verbose_name="content (Spanish)")),
                ("content_en", models.TextField(verbose_name="content (English)")),
                (
                    "ai_context",
                    models.TextField(
                        blank=True,
                        help_text="Condensed version for AI context injection",
                        verbose_name="AI context",
                    ),
                ),
                ("keywords", models.JSONField(default=list, verbose_name="keywords")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Higher = more important for AI context",
                        verbose_name="priority",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="knowledge.knowledgecategory",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "knowledge article",
                "verbose_name_plural": "knowledge articles",
                "ordering": ["-priority", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500, verbose_name="question")),
                (
                    "question_es",
                    models.CharField(max_length=500, verbose_name="question (Spanish)"),
                ),
                (
                    "question_en",
                    models.CharField(max_length=500, verbose_name="question (English)"),
                ),
                ("answer", models.TextField(verbose_name="answer")),
                ("answer_es", models.TextField(verbose_name="answer (Spanish)")),
                ("answer_en", models.TextField(verbose_name="answer (English)")),
                ("order", models.IntegerField(default=0, verbose_name="order")),
                (
                    "view_count",
                    models.IntegerField(default=0, verbose_name="view count"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="featured"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="knowledge.knowledgecategory",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ArticleVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField(verbose_name="version number")),
                ("content_es", models.TextField(verbose_name="content (Spanish)")),
                ("content_en", models.TextField(verbose_name="content (English)")),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="changed at"),
                ),
                (
                    "change_summary",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="change summary"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="changed by",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="knowledge.knowledgearticle",
                        verbose_name="article",
                    ),
                ),
            ],
            options={
                "verbose_name": "article version",
                "verbose_name_plural": "article versions",
                "ordering": ["-version_number"],
                "unique_together": {("article", "version_number")},
            },
        ),
    ]
