# Generated by Django 5.2.9 on 2025-12-26 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowedCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 country code (e.g., US, GB)",
                        max_length=2,
                        unique=True,
                    ),
                ),
                ("country_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Allowed Country",
                "verbose_name_plural": "Allowed Countries",
                "ordering": ["country_name"],
            },
        ),
        migrations.CreateModel(
            name="WAFConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate_limit_enabled", models.BooleanField(default=True)),
                (
                    "rate_limit_requests",
                    models.PositiveIntegerField(
                        default=200, help_text="Maximum requests per IP per minute"
                    ),
                ),
                (
                    "rate_limit_window",
                    models.PositiveIntegerField(
                        default=60, help_text="Time window in seconds"
                    ),
                ),
                ("auto_ban_enabled", models.BooleanField(default=True)),
                (
                    "max_strikes",
                    models.PositiveIntegerField(
                        default=5, help_text="Security events before auto-ban"
                    ),
                ),
                (
                    "ban_duration",
                    models.PositiveIntegerField(
                        default=900,
                        help_text="Ban duration in seconds (default 15 min)",
                    ),
                ),
                ("pattern_detection_enabled", models.BooleanField(default=True)),
                ("block_sql_injection", models.BooleanField(default=True)),
                ("block_xss", models.BooleanField(default=True)),
                ("block_path_traversal", models.BooleanField(default=True)),
                ("geo_blocking_enabled", models.BooleanField(default=False)),
                (
                    "security_log_path",
                    models.CharField(
                        default="/var/log/django/security.log",
                        help_text="Path for fail2ban-compatible security log",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "WAF Configuration",
                "verbose_name_plural": "WAF Configuration",
            },
        ),
        migrations.CreateModel(
            name="BannedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("reason", models.CharField(max_length=200)),
                ("strike_count", models.PositiveIntegerField(default=0)),
                ("auto_banned", models.BooleanField(default=False)),
                ("banned_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("permanent", models.BooleanField(default=False)),
                ("last_request_path", models.CharField(blank=True, max_length=500)),
                ("last_user_agent", models.CharField(blank=True, max_length=500)),
                (
                    "banned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Banned IP",
                "verbose_name_plural": "Banned IPs",
                "ordering": ["-banned_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("failed_login", "Failed Login"),
                            ("invalid_token", "Invalid Token"),
                            ("rate_limit", "Rate Limit Exceeded"),
                            ("sqli", "SQL Injection Detected"),
                            ("xss", "XSS Detected"),
                            ("path_traversal", "Path Traversal"),
                            ("banned_access", "Banned IP Access"),
                            ("geo_blocked", "Geo-blocked"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("path", models.CharField(max_length=500)),
                ("method", models.CharField(default="GET", max_length=10)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("details", models.TextField(blank=True)),
                (
                    "action_taken",
                    models.CharField(
                        default="logged",
                        help_text="Action taken (logged, blocked, banned)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Event",
                "verbose_name_plural": "Security Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="waf_securit_ip_addr_a92d25_idx",
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="waf_securit_event_t_642d9e_idx",
                    ),
                ],
            },
        ),
    ]
