# Generated by Django 5.2.9 on 2025-12-27 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="phone"),
                ),
                (
                    "address_line1",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 1"
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 2"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="state/province"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Mexico", max_length=100, verbose_name="country"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("household", "Household"),
                            ("family", "Family"),
                            ("partnership", "Partnership"),
                            ("other", "Other"),
                        ],
                        default="household",
                        max_length=20,
                        verbose_name="group type",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "group",
                "verbose_name_plural": "groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="phone"),
                ),
                (
                    "address_line1",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 1"
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 2"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="state/province"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Mexico", max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="middle name"
                    ),
                ),
                (
                    "preferred_name",
                    models.CharField(
                        blank=True,
                        help_text="What this person prefers to be called",
                        max_length=150,
                        verbose_name="preferred name",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated from name or manually set",
                        max_length=300,
                        verbose_name="display name",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth"
                    ),
                ),
                (
                    "date_of_death",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of death"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "person",
                "verbose_name_plural": "people",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="phone"),
                ),
                (
                    "address_line1",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 1"
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 2"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="state/province"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Mexico", max_length=100, verbose_name="country"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("clinic", "Veterinary Clinic"),
                            ("rescue", "Animal Rescue/Shelter"),
                            ("supplier", "Supplier/Distributor"),
                            ("school", "School/Institution"),
                            ("partner", "Business Partner"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="organization type",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="RFC in Mexico",
                        max_length=20,
                        verbose_name="tax ID",
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="legal name"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "api_account",
                    models.OneToOneField(
                        blank=True,
                        help_text="Service account for API access",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organization_account",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="API account",
                    ),
                ),
            ],
            options={
                "verbose_name": "organization",
                "verbose_name_plural": "organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PartyURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url_type",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("twitter", "Twitter/X"),
                            ("linkedin", "LinkedIn"),
                            ("youtube", "YouTube"),
                            ("tiktok", "TikTok"),
                            ("whatsapp", "WhatsApp Business"),
                            ("google_maps", "Google Maps"),
                            ("yelp", "Yelp"),
                            ("github", "GitHub"),
                            ("portfolio", "Portfolio"),
                            ("blog", "Blog"),
                            ("other", "Other"),
                        ],
                        default="website",
                        max_length=20,
                        verbose_name="URL type",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="primary"),
                ),
                ("url", models.URLField(max_length=500, verbose_name="URL")),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Social media handle without @ symbol",
                        max_length=100,
                        verbose_name="username/handle",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text='Custom label like "Personal Blog" or "Company LinkedIn"',
                        max_length=100,
                        verbose_name="label",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Verified ownership of this URL",
                        verbose_name="verified",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Show on public profiles",
                        verbose_name="public",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urls",
                        to="parties.group",
                        verbose_name="group",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urls",
                        to="parties.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urls",
                        to="parties.person",
                        verbose_name="person",
                    ),
                ),
            ],
            options={
                "verbose_name": "URL",
                "verbose_name_plural": "URLs",
                "ordering": ["-is_primary", "url_type", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartyRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("employee", "Employee"),
                            ("contractor_individual", "Individual Contractor (1099)"),
                            ("contact", "Contact"),
                            ("owner", "Owner/Executive"),
                            ("contractor_org", "Contractor Organization"),
                            ("vendor", "Vendor/Supplier"),
                            ("partner", "Business Partner"),
                            ("client", "Client/Customer"),
                            ("member", "Member"),
                            ("head", "Head of Household"),
                            ("spouse", "Spouse/Partner"),
                            ("dependent", "Dependent"),
                            ("emergency_contact", "Emergency Contact"),
                            ("guardian", "Guardian"),
                            ("parent", "Parent"),
                            ("child", "Child"),
                            ("sibling", "Sibling"),
                        ],
                        max_length=30,
                        verbose_name="relationship type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Job title or role description",
                        max_length=100,
                        verbose_name="title",
                    ),
                ),
                (
                    "contract_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="contract start"
                    ),
                ),
                (
                    "contract_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="contract end"
                    ),
                ),
                (
                    "contract_signed",
                    models.BooleanField(default=False, verbose_name="contract signed"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary relationship of this type",
                        verbose_name="primary",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_from",
                        to="parties.organization",
                        verbose_name="from organization",
                    ),
                ),
                (
                    "to_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_to",
                        to="parties.group",
                        verbose_name="to group",
                    ),
                ),
                (
                    "to_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_to",
                        to="parties.organization",
                        verbose_name="to organization",
                    ),
                ),
                (
                    "from_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_from",
                        to="parties.person",
                        verbose_name="from person",
                    ),
                ),
                (
                    "to_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_to",
                        to="parties.person",
                        verbose_name="to person",
                    ),
                ),
            ],
            options={
                "verbose_name": "party relationship",
                "verbose_name_plural": "party relationships",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="group",
            name="primary_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_for_groups",
                to="parties.person",
                verbose_name="primary contact",
            ),
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("work", "Work"),
                            ("billing", "Billing"),
                            ("newsletter", "Newsletter"),
                            ("other", "Other"),
                        ],
                        default="personal",
                        max_length=20,
                        verbose_name="email type",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="primary"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="email address"),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=100, verbose_name="label"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="verified"),
                ),
                (
                    "receives_marketing",
                    models.BooleanField(
                        default=False, verbose_name="receives marketing"
                    ),
                ),
                (
                    "receives_transactional",
                    models.BooleanField(
                        default=True, verbose_name="receives transactional"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_addresses",
                        to="parties.group",
                        verbose_name="group",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_addresses",
                        to="parties.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_addresses",
                        to="parties.person",
                        verbose_name="person",
                    ),
                ),
            ],
            options={
                "verbose_name": "email address",
                "verbose_name_plural": "email addresses",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Demographics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("non_binary", "Non-binary"),
                            ("prefer_not_say", "Prefer not to say"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="gender",
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                            ("separated", "Separated"),
                            ("domestic_partner", "Domestic Partnership"),
                            ("prefer_not_say", "Prefer not to say"),
                        ],
                        max_length=20,
                        verbose_name="marital status",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nationality"
                    ),
                ),
                (
                    "country_of_birth",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="country of birth"
                    ),
                ),
                (
                    "ethnicity",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ethnicity"
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        default="es",
                        help_text="ISO 639-1 code",
                        max_length=10,
                        verbose_name="preferred language",
                    ),
                ),
                (
                    "additional_languages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of ISO 639-1 codes",
                        verbose_name="additional languages",
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="education level"
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="occupation"
                    ),
                ),
                (
                    "household_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of people in household",
                        null=True,
                        verbose_name="household size",
                    ),
                ),
                (
                    "has_children",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="has children"
                    ),
                ),
                (
                    "number_of_children",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="number of children"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demographics",
                        to="parties.person",
                        verbose_name="person",
                    ),
                ),
            ],
            options={
                "verbose_name": "demographics",
                "verbose_name_plural": "demographics",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("work", "Work"),
                            ("mailing", "Mailing"),
                            ("billing", "Billing"),
                            ("shipping", "Shipping"),
                            ("other", "Other"),
                        ],
                        default="home",
                        max_length=20,
                        verbose_name="address type",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="primary"),
                ),
                (
                    "line1",
                    models.CharField(max_length=255, verbose_name="address line 1"),
                ),
                (
                    "line2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 2"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="state/province"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Mexico", max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="longitude",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text='Custom label like "Mom\'s House" or "Downtown Office"',
                        max_length=100,
                        verbose_name="label",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="verified"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="parties.group",
                        verbose_name="group",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="parties.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="parties.person",
                        verbose_name="person",
                    ),
                ),
            ],
            options={
                "verbose_name": "address",
                "verbose_name_plural": "addresses",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_type",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("home", "Home"),
                            ("work", "Work"),
                            ("fax", "Fax"),
                            ("whatsapp", "WhatsApp"),
                            ("other", "Other"),
                        ],
                        default="mobile",
                        max_length=20,
                        verbose_name="phone type",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="primary"),
                ),
                (
                    "country_code",
                    models.CharField(
                        default="+52",
                        help_text="e.g., +52 for Mexico, +1 for US",
                        max_length=5,
                        verbose_name="country code",
                    ),
                ),
                ("number", models.CharField(max_length=20, verbose_name="number")),
                (
                    "extension",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="extension"
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=100, verbose_name="label"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="verified"),
                ),
                (
                    "can_receive_sms",
                    models.BooleanField(default=True, verbose_name="can receive SMS"),
                ),
                (
                    "can_receive_whatsapp",
                    models.BooleanField(
                        default=False, verbose_name="can receive WhatsApp"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_numbers",
                        to="parties.group",
                        verbose_name="group",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_numbers",
                        to="parties.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_numbers",
                        to="parties.person",
                        verbose_name="person",
                    ),
                ),
            ],
            options={
                "verbose_name": "phone number",
                "verbose_name_plural": "phone numbers",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
    ]
