# Generated by Django 5.2.9 on 2025-12-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="phone_can_receive_sms",
            field=models.BooleanField(default=True, verbose_name="can receive SMS"),
        ),
        migrations.AddField(
            model_name="person",
            name="phone_has_whatsapp",
            field=models.BooleanField(default=False, verbose_name="has WhatsApp"),
        ),
        migrations.AddField(
            model_name="person",
            name="phone_is_mobile",
            field=models.BooleanField(default=True, verbose_name="is mobile"),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="primary email"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="primary phone"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="postal_code",
            field=models.CharField(
                blank=True,
                help_text="Primary area/zip code for this person",
                max_length=10,
                verbose_name="postal code",
            ),
        ),
    ]
