# Generated by Django 5.2.9 on 2025-12-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0002_person_phone_can_receive_sms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="address_is_billing",
            field=models.BooleanField(default=False, verbose_name="billing address"),
        ),
        migrations.AddField(
            model_name="person",
            name="address_is_home",
            field=models.BooleanField(default=True, verbose_name="home address"),
        ),
        migrations.AddField(
            model_name="person",
            name="address_is_shipping",
            field=models.BooleanField(default=False, verbose_name="shipping address"),
        ),
        migrations.AlterField(
            model_name="person",
            name="country",
            field=models.CharField(
                blank=True, default="Mexico", max_length=100, verbose_name="country"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="state",
            field=models.CharField(blank=True, max_length=100, verbose_name="state"),
        ),
    ]
