# Generated by Django 5.2.9 on 2025-12-27 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Room identifier, e.g., "Room 1", "Exam A", "Surgery"',
                        max_length=30,
                        verbose_name="name",
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("exam", "Exam Room"),
                            ("surgery", "Surgery"),
                            ("imaging", "Imaging"),
                            ("treatment", "Treatment"),
                            ("isolation", "Isolation"),
                        ],
                        default="exam",
                        max_length=20,
                        verbose_name="room type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Set to False to retire a room without deleting",
                        verbose_name="active",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in room selection lists (lower first)",
                        verbose_name="display order",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_rooms",
                        to="locations.location",
                        verbose_name="location",
                    ),
                ),
            ],
            options={
                "verbose_name": "exam room",
                "verbose_name_plural": "exam rooms",
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["location", "is_active", "display_order"],
                        name="locations_e_locatio_76e7f7_idx",
                    )
                ],
                "unique_together": {("location", "name")},
            },
        ),
    ]
