# Generated by Django 5.2.9 on 2025-12-26 02:50

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0002_clinicsettings_clinicalnote_shift_task_timeentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicsettings",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.core.storage.clinic_logo_path
            ),
        ),
    ]
