# Generated by Django 5.2.9 on 2025-12-26 20:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_add_tax_and_sat_models"),
        ("practice", "0003_alter_clinicsettings_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcedureCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique identifier (e.g., 'surgery', 'dental')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_es", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Procedure Category",
                "verbose_name_plural": "Procedure Categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="VetProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Internal procedure code (e.g., 'CONSULT-GEN')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_es", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Standard price for this procedure",
                        max_digits=10,
                    ),
                ),
                (
                    "price_varies",
                    models.BooleanField(
                        default=False,
                        help_text="Price depends on factors (size, complexity, etc.)",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=30, help_text="Expected duration in minutes"
                    ),
                ),
                ("requires_appointment", models.BooleanField(default=True)),
                ("requires_hospitalization", models.BooleanField(default=False)),
                ("requires_anesthesia", models.BooleanField(default=False)),
                (
                    "requires_vet_license",
                    models.BooleanField(
                        default=True,
                        help_text="Must be performed by licensed veterinarian",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_visible_online",
                    models.BooleanField(
                        default=True, help_text="Show in online booking system"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedures",
                        to="practice.procedurecategory",
                    ),
                ),
                (
                    "sat_product_code",
                    models.ForeignKey(
                        blank=True,
                        help_text="SAT Clave Producto for CFDI invoicing",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.satproductcode",
                    ),
                ),
                (
                    "sat_unit_code",
                    models.ForeignKey(
                        blank=True,
                        help_text="SAT Clave Unidad for CFDI invoicing",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.satunitcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veterinary Procedure",
                "verbose_name_plural": "Veterinary Procedures",
                "ordering": ["category", "name"],
            },
        ),
    ]
