# Generated by Django 5.2.9 on 2025-12-26 21:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_delete_service_stocklevels"),
        ("practice", "0004_procedurecategory_vetprocedure"),
    ]

    operations = [
        migrations.AddField(
            model_name="vetprocedure",
            name="qualified_providers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Staff members qualified to perform this procedure",
                related_name="qualified_procedures",
                to="practice.staffprofile",
            ),
        ),
        migrations.CreateModel(
            name="ProcedureConsumable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Quantity consumed per procedure",
                        max_digits=10,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="If true, procedure cannot be performed without this item in stock",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="Optional notes (e.g., 'Use 3ml syringe for small dogs')",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        help_text="Inventory item consumed during this procedure",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedure_uses",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumables",
                        to="practice.vetprocedure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedure Consumable",
                "verbose_name_plural": "Procedure Consumables",
                "ordering": ["procedure", "inventory_item"],
                "unique_together": {("procedure", "inventory_item")},
            },
        ),
    ]
