# Generated by Django 5.2.9 on 2025-12-27 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0003_add_task_and_employee_links"),
        ("practice", "0005_add_qualified_providers_consumables"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to HR Employee record for unified tracking",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_profiles",
                to="hr.employee",
            ),
        ),
    ]
