# Generated by Django 5.2.9 on 2025-12-27 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0006_add_task_and_employee_links"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffprofile",
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "verbose_name": "staff profile (deprecated)",
                "verbose_name_plural": "staff profiles (deprecated)",
            },
        ),
        migrations.CreateModel(
            name="VetCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credential_type",
                    models.CharField(
                        choices=[
                            ("veterinarian", "Veterinarian (DVM/MVZ)"),
                            ("vet_tech", "Veterinary Technician"),
                            ("pharmacy_tech", "Pharmacy Technician"),
                            ("specialist", "Veterinary Specialist"),
                        ],
                        default="veterinarian",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text='Professional title (e.g., "DVM", "MVZ", "Veterinary Technician")',
                        max_length=100,
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        help_text='Specialty area (e.g., "Oncology", "Surgery", "Dentistry")',
                        max_length=100,
                    ),
                ),
                ("license_number", models.CharField(blank=True, max_length=50)),
                (
                    "license_state",
                    models.CharField(
                        blank=True, help_text="Issuing state/country", max_length=50
                    ),
                ),
                ("license_expiry", models.DateField(blank=True, null=True)),
                ("dea_number", models.CharField(blank=True, max_length=20)),
                ("dea_expiration", models.DateField(blank=True, null=True)),
                (
                    "can_prescribe",
                    models.BooleanField(
                        default=False, help_text="Can prescribe medications"
                    ),
                ),
                (
                    "can_dispense",
                    models.BooleanField(
                        default=False, help_text="Can dispense medications"
                    ),
                ),
                (
                    "can_handle_controlled",
                    models.BooleanField(
                        default=False, help_text="Can handle controlled substances"
                    ),
                ),
                (
                    "can_perform_surgery",
                    models.BooleanField(
                        default=False, help_text="Can perform surgical procedures"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vet_credentials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="person",
                    ),
                ),
            ],
            options={
                "verbose_name": "veterinary credentials",
                "verbose_name_plural": "veterinary credentials",
                "ordering": ["person__first_name", "person__last_name"],
            },
        ),
    ]
