# Generated by Django 5.2.9 on 2025-12-27 09:13

import apps.core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0007_pet_owner_group_pet_owner_organization_and_more"),
        ("practice", "0007_alter_staffprofile_options_vetcredentials"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="condition name"),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("allergy", "Allergy"),
                            ("chronic", "Chronic Condition"),
                            ("injury", "Injury"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "diagnosed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="diagnosed date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "diagnosed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conditions_diagnosed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="diagnosed by",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_conditions",
                        to="pets.pet",
                        verbose_name="pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "medical condition",
                "verbose_name_plural": "medical conditions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_number",
                    models.CharField(
                        help_text="Practice-specific patient ID",
                        max_length=20,
                        unique=True,
                        verbose_name="patient number",
                    ),
                ),
                (
                    "first_visit_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="first visit date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("transferred", "Transferred"),
                            ("deceased", "Deceased"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "referring_practice",
                    models.CharField(
                        blank=True,
                        help_text="If referred from another veterinary practice",
                        max_length=200,
                        verbose_name="referring practice",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Practice-specific medical notes",
                        verbose_name="medical notes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_record",
                        to="pets.pet",
                        verbose_name="pet",
                    ),
                ),
                (
                    "primary_veterinarian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_patients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="primary veterinarian",
                    ),
                ),
            ],
            options={
                "verbose_name": "patient record",
                "verbose_name_plural": "patient records",
                "ordering": ["patient_number"],
            },
        ),
        migrations.CreateModel(
            name="Vaccination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vaccine_name",
                    models.CharField(max_length=200, verbose_name="vaccine name"),
                ),
                (
                    "date_administered",
                    models.DateField(verbose_name="date administered"),
                ),
                (
                    "next_due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="next due date"
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="batch number"
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="manufacturer"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "reminder_sent",
                    models.BooleanField(default=False, verbose_name="reminder sent"),
                ),
                (
                    "reminder_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reminder sent at"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "administered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vaccinations_administered",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="administered by",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccination_records",
                        to="pets.pet",
                        verbose_name="pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "vaccination",
                "verbose_name_plural": "vaccinations",
                "ordering": ["-date_administered"],
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="visit date")),
                (
                    "reason",
                    models.CharField(max_length=500, verbose_name="reason for visit"),
                ),
                ("diagnosis", models.TextField(blank=True, verbose_name="diagnosis")),
                ("treatment", models.TextField(blank=True, verbose_name="treatment")),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="weight at visit (kg)",
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="temperature (°C)",
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="follow-up date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_records",
                        to="pets.pet",
                        verbose_name="pet",
                    ),
                ),
                (
                    "veterinarian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visits_as_vet",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="veterinarian",
                    ),
                ),
            ],
            options={
                "verbose_name": "visit",
                "verbose_name_plural": "visits",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="medication name"),
                ),
                ("dosage", models.CharField(max_length=100, verbose_name="dosage")),
                (
                    "frequency",
                    models.CharField(max_length=100, verbose_name="frequency"),
                ),
                (
                    "route",
                    models.CharField(
                        blank=True,
                        help_text="e.g., oral, injection, topical",
                        max_length=50,
                        verbose_name="route of administration",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="end date"),
                ),
                (
                    "refills_remaining",
                    models.PositiveIntegerField(
                        default=0, verbose_name="refills remaining"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_records",
                        to="pets.pet",
                        verbose_name="pet",
                    ),
                ),
                (
                    "prescribing_vet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medications_prescribed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="prescribing veterinarian",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescribed_medications",
                        to="practice.visit",
                        verbose_name="related visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "medication",
                "verbose_name_plural": "medications",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="MedicalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("lab_result", "Lab Result"),
                            ("xray", "X-Ray"),
                            ("ultrasound", "Ultrasound"),
                            ("photo", "Clinical Photo"),
                            ("certificate", "Certificate"),
                            ("prescription", "Prescription"),
                            ("referral", "Referral"),
                            ("discharge", "Discharge Summary"),
                            ("consent", "Consent Form"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="document type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.core.storage.pet_document_path,
                        verbose_name="file",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "visible_to_owner",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the pet owner can see this document",
                        verbose_name="visible to owner",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_documents",
                        to="pets.pet",
                        verbose_name="pet",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_documents_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="practice.visit",
                        verbose_name="related visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "medical document",
                "verbose_name_plural": "medical documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeightRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="weight (kg)"
                    ),
                ),
                ("recorded_date", models.DateField(verbose_name="recorded date")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_history",
                        to="pets.pet",
                        verbose_name="pet",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weight_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recorded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "weight record",
                "verbose_name_plural": "weight records",
                "ordering": ["-recorded_date"],
            },
        ),
    ]
