# Generated by Django 5.2.9 on 2025-12-24 01:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0004_alter_medication_prescribing_vet"),
        ("pharmacy", "0001_initial"),
        ("store", "0002_add_payment_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("store", "Store Floor"),
                            ("pharmacy", "Pharmacy"),
                            ("clinic", "Clinic Storage"),
                            ("refrigerated", "Refrigerated"),
                            ("controlled", "Controlled Substances"),
                            ("warehouse", "Warehouse/Backstock"),
                        ],
                        default="store",
                        max_length=20,
                        verbose_name="location type",
                    ),
                ),
                (
                    "requires_temperature_control",
                    models.BooleanField(
                        default=False, verbose_name="requires temperature control"
                    ),
                ),
                (
                    "requires_restricted_access",
                    models.BooleanField(
                        default=False, verbose_name="requires restricted access"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "stock location",
                "verbose_name_plural": "stock locations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "code",
                    models.CharField(blank=True, max_length=50, verbose_name="code"),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="contact name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="phone"),
                ),
                ("address", models.TextField(blank=True, verbose_name="address")),
                (
                    "rfc",
                    models.CharField(
                        blank=True,
                        help_text="Tax ID",
                        max_length=13,
                        verbose_name="RFC",
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        help_text="net30, prepaid, etc.",
                        max_length=50,
                        verbose_name="payment terms",
                    ),
                ),
                (
                    "lead_time_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="lead time (days)"
                    ),
                ),
                (
                    "categories",
                    models.JSONField(
                        default=list,
                        help_text="Categories this supplier provides",
                        verbose_name="categories",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_preferred",
                    models.BooleanField(default=False, verbose_name="preferred"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "supplier",
                "verbose_name_plural": "suppliers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "po_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="PO number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("confirmed", "Confirmed by Supplier"),
                            ("shipped", "Shipped"),
                            ("partial", "Partially Received"),
                            ("received", "Fully Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "order_date",
                    models.DateField(blank=True, null=True, verbose_name="order date"),
                ),
                (
                    "expected_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="expected date"
                    ),
                ),
                (
                    "received_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="received date"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="subtotal",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="tax",
                    ),
                ),
                (
                    "shipping",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="shipping",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="total",
                    ),
                ),
                (
                    "shipping_address",
                    models.TextField(blank=True, verbose_name="shipping address"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="internal notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="approved by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "delivery_location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_orders",
                        to="inventory.stocklocation",
                        verbose_name="delivery location",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="inventory.supplier",
                        verbose_name="supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "purchase order",
                "verbose_name_plural": "purchase orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_ordered",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="quantity ordered"
                    ),
                ),
                (
                    "quantity_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="quantity received",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="unit cost"
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="line total"
                    ),
                ),
                (
                    "supplier_sku",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="supplier SKU"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order_lines",
                        to="store.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.purchaseorder",
                        verbose_name="purchase order",
                    ),
                ),
            ],
            options={
                "verbose_name": "purchase order line",
                "verbose_name_plural": "purchase order lines",
            },
        ),
        migrations.CreateModel(
            name="StockBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(max_length=100, verbose_name="batch number"),
                ),
                (
                    "lot_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="lot number"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="serial number"
                    ),
                ),
                (
                    "initial_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="initial quantity"
                    ),
                ),
                (
                    "current_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="current quantity"
                    ),
                ),
                (
                    "manufacture_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="manufacture date"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="expiry date"),
                ),
                ("received_date", models.DateField(verbose_name="received date")),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="unit cost"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("low", "Low Stock"),
                            ("depleted", "Depleted"),
                            ("expired", "Expired"),
                            ("recalled", "Recalled"),
                            ("damaged", "Damaged"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="store.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batches",
                        to="inventory.purchaseorder",
                        verbose_name="purchase order",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="inventory.stocklocation",
                        verbose_name="location",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batches",
                        to="inventory.supplier",
                        verbose_name="supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock batch",
                "verbose_name_plural": "stock batches",
                "ordering": ["expiry_date", "received_date"],
            },
        ),
        migrations.CreateModel(
            name="ControlledSubstanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("receive", "Received"),
                            ("dispense", "Dispensed"),
                            ("waste", "Waste/Disposal"),
                            ("return", "Returned"),
                            ("transfer", "Transferred"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                        verbose_name="log type",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="quantity"
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="balance after"
                    ),
                ),
                (
                    "waste_reason",
                    models.TextField(blank=True, verbose_name="waste reason"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controlled_substance_logs",
                        to="pets.pet",
                        verbose_name="pet",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controlled_logs",
                        to="pharmacy.prescription",
                        verbose_name="prescription",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controlled_logs",
                        to="store.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controlled_substance_recordings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recorded by",
                    ),
                ),
                (
                    "waste_witnessed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="waste witnessed by",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controlled_logs",
                        to="inventory.stockbatch",
                        verbose_name="batch",
                    ),
                ),
            ],
            options={
                "verbose_name": "controlled substance log",
                "verbose_name_plural": "controlled substance logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count_date", models.DateField(verbose_name="count date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "In Progress"),
                            ("submitted", "Submitted for Review"),
                            ("approved", "Approved"),
                            ("posted", "Posted to Stock"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "count_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Count"),
                            ("cycle", "Cycle Count"),
                            ("spot", "Spot Check"),
                        ],
                        default="full",
                        max_length=20,
                        verbose_name="count type",
                    ),
                ),
                (
                    "product_filter",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Filter to specific products/categories",
                        verbose_name="product filter",
                    ),
                ),
                (
                    "total_products",
                    models.IntegerField(default=0, verbose_name="total products"),
                ),
                (
                    "products_counted",
                    models.IntegerField(default=0, verbose_name="products counted"),
                ),
                (
                    "discrepancies_found",
                    models.IntegerField(default=0, verbose_name="discrepancies found"),
                ),
                (
                    "discrepancy_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="discrepancy value",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="approved at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="approved by",
                    ),
                ),
                (
                    "counted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="counted by",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_counts",
                        to="inventory.stocklocation",
                        verbose_name="location",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock count",
                "verbose_name_plural": "stock counts",
            },
        ),
        migrations.CreateModel(
            name="StockCountLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="system quantity"
                    ),
                ),
                (
                    "counted_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="counted quantity",
                    ),
                ),
                (
                    "discrepancy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="discrepancy",
                    ),
                ),
                (
                    "discrepancy_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="discrepancy value",
                    ),
                ),
                (
                    "adjustment_reason",
                    models.TextField(blank=True, verbose_name="adjustment reason"),
                ),
                (
                    "adjustment_posted",
                    models.BooleanField(
                        default=False, verbose_name="adjustment posted"
                    ),
                ),
                (
                    "counted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="counted at"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="count_lines",
                        to="inventory.stockbatch",
                        verbose_name="batch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="count_lines",
                        to="store.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "stock_count",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.stockcount",
                        verbose_name="stock count",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock count line",
                "verbose_name_plural": "stock count lines",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("receive", "Received from Supplier"),
                            ("return_customer", "Customer Return"),
                            ("transfer_in", "Transfer In"),
                            ("adjustment_add", "Adjustment (Add)"),
                            ("sale", "Sale"),
                            ("dispense", "Prescription Dispensed"),
                            ("return_supplier", "Return to Supplier"),
                            ("transfer_out", "Transfer Out"),
                            ("adjustment_remove", "Adjustment (Remove)"),
                            ("expired", "Expired/Disposed"),
                            ("damaged", "Damaged"),
                            ("loss", "Loss/Shrinkage"),
                            ("sample", "Sample/Promo"),
                        ],
                        max_length=20,
                        verbose_name="movement type",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="quantity"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="unit cost",
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text="order, invoice, purchase_order, prescription, adjustment, etc.",
                        max_length=50,
                        verbose_name="reference type",
                    ),
                ),
                (
                    "reference_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="reference ID"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="reason")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "authorized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authorized_movements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="authorized by",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="inventory.stockbatch",
                        verbose_name="batch",
                    ),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements_out",
                        to="inventory.stocklocation",
                        verbose_name="from location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="store.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_movements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recorded by",
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements_in",
                        to="inventory.stocklocation",
                        verbose_name="to location",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock movement",
                "verbose_name_plural": "stock movements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="quantity",
                    ),
                ),
                (
                    "reserved_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Reserved for pending orders",
                        max_digits=10,
                        verbose_name="reserved quantity",
                    ),
                ),
                (
                    "min_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Override product default",
                        max_digits=10,
                        null=True,
                        verbose_name="minimum level",
                    ),
                ),
                (
                    "reorder_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="reorder quantity",
                    ),
                ),
                (
                    "last_counted",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last counted"
                    ),
                ),
                (
                    "last_movement",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last movement"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_levels",
                        to="store.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_levels",
                        to="inventory.stocklocation",
                        verbose_name="location",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock level",
                "verbose_name_plural": "stock levels",
                "unique_together": {("product", "location")},
            },
        ),
        migrations.CreateModel(
            name="ReorderRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_level",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="minimum level"
                    ),
                ),
                (
                    "reorder_point",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="reorder point"
                    ),
                ),
                (
                    "reorder_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="reorder quantity"
                    ),
                ),
                (
                    "max_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="maximum level",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "auto_create_po",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically create purchase order when below reorder point",
                        verbose_name="auto create PO",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reorder_rules",
                        to="store.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="If null, applies to all locations",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reorder_rules",
                        to="inventory.stocklocation",
                        verbose_name="location",
                    ),
                ),
                (
                    "preferred_supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reorder_rules",
                        to="inventory.supplier",
                        verbose_name="preferred supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "reorder rule",
                "verbose_name_plural": "reorder rules",
                "unique_together": {("product", "location")},
            },
        ),
        migrations.CreateModel(
            name="ProductSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_sku",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="supplier SKU"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="unit cost"
                    ),
                ),
                (
                    "minimum_order_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        max_digits=10,
                        verbose_name="minimum order quantity",
                    ),
                ),
                (
                    "is_preferred",
                    models.BooleanField(default=False, verbose_name="preferred"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "last_ordered",
                    models.DateField(
                        blank=True, null=True, verbose_name="last ordered"
                    ),
                ),
                (
                    "last_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="last price",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="store.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="inventory.supplier",
                        verbose_name="supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "product supplier",
                "verbose_name_plural": "product suppliers",
                "unique_together": {("product", "supplier")},
            },
        ),
    ]
