# Generated by Django 5.2.9 on 2025-12-26 16:27
# Modified to handle CharField -> ForeignKey migration

import django.db.models.deletion
from django.db import migrations, models


def migrate_location_types(apps, schema_editor):
    """Migrate old CharField location_type values to LocationType FK."""
    LocationType = apps.get_model('inventory', 'LocationType')
    StockLocation = apps.get_model('inventory', 'StockLocation')

    # Map old choices to new LocationType records
    type_mapping = {
        'store': {'name': 'Store Floor', 'code': 'store'},
        'pharmacy': {'name': 'Pharmacy', 'code': 'pharmacy', 'requires_restricted_access': True},
        'clinic': {'name': 'Clinic Storage', 'code': 'clinic'},
        'refrigerated': {'name': 'Refrigerated', 'code': 'refrigerated', 'requires_temperature_control': True},
        'controlled': {'name': 'Controlled Substances', 'code': 'controlled', 'requires_restricted_access': True},
        'warehouse': {'name': 'Warehouse/Backstock', 'code': 'warehouse'},
    }

    # Create LocationType records for existing location_type values
    for old_value, type_data in type_mapping.items():
        LocationType.objects.get_or_create(
            code=type_data['code'],
            defaults={
                'name': type_data['name'],
                'requires_temperature_control': type_data.get('requires_temperature_control', False),
                'requires_restricted_access': type_data.get('requires_restricted_access', False),
                'source_module': 'inventory',
            }
        )

    # Update StockLocation records to use the new FK
    for location in StockLocation.objects.all():
        old_type = location.location_type_old
        if old_type and old_type in type_mapping:
            location_type = LocationType.objects.get(code=old_type)
            location.location_type_new = location_type
            location.save()


def reverse_migrate_location_types(apps, schema_editor):
    """Reverse migration - copy FK back to CharField."""
    StockLocation = apps.get_model('inventory', 'StockLocation')

    for location in StockLocation.objects.all():
        if location.location_type_new:
            location.location_type_old = location.location_type_new.code
            location.save()


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        # Step 1: Create LocationType model
        migrations.CreateModel(
            name="LocationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "requires_temperature_control",
                    models.BooleanField(
                        default=False,
                        help_text="Locations of this type require temperature monitoring",
                        verbose_name="requires temperature control",
                    ),
                ),
                (
                    "requires_restricted_access",
                    models.BooleanField(
                        default=False,
                        help_text="Locations of this type require special access permissions",
                        verbose_name="requires restricted access",
                    ),
                ),
                (
                    "source_module",
                    models.CharField(
                        blank=True,
                        help_text="Module that created this type (e.g., pharmacy, inventory)",
                        max_length=50,
                        verbose_name="source module",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "location type",
                "verbose_name_plural": "location types",
                "ordering": ["name"],
            },
        ),

        # Step 2: Rename old location_type CharField to location_type_old
        migrations.RenameField(
            model_name='stocklocation',
            old_name='location_type',
            new_name='location_type_old',
        ),

        # Step 3: Add new location_type FK field
        migrations.AddField(
            model_name='stocklocation',
            name='location_type_new',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='locations',
                to='inventory.locationtype',
                verbose_name='location type',
            ),
        ),

        # Step 4: Migrate data from old to new field
        migrations.RunPython(migrate_location_types, reverse_migrate_location_types),

        # Step 5: Remove old CharField
        migrations.RemoveField(
            model_name='stocklocation',
            name='location_type_old',
        ),

        # Step 6: Rename new FK to final name
        migrations.RenameField(
            model_name='stocklocation',
            old_name='location_type_new',
            new_name='location_type',
        ),
    ]
