# Generated by Django 5.2.9 on 2025-12-26 17:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
        ("billing", "0003_add_tax_and_sat_models"),
        ("inventory", "0002_add_location_type_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(max_length=50, unique=True, verbose_name="SKU"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("resale", "Resale Product"),
                            ("supply", "Operational Supply"),
                            ("consumable", "Consumable"),
                            ("equipment", "Equipment/Asset"),
                            ("raw_material", "Raw Material"),
                        ],
                        max_length=20,
                        verbose_name="item type",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="cost price",
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="sale price",
                    ),
                ),
                (
                    "track_inventory",
                    models.BooleanField(default=True, verbose_name="track inventory"),
                ),
                (
                    "reorder_point",
                    models.PositiveIntegerField(
                        default=0, verbose_name="reorder point"
                    ),
                ),
                (
                    "reorder_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="reorder quantity"
                    ),
                ),
                (
                    "is_depreciable",
                    models.BooleanField(default=False, verbose_name="depreciable"),
                ),
                (
                    "useful_life_months",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="useful life (months)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "cogs_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="COGS account for resale items",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cogs_items",
                        to="accounting.account",
                        verbose_name="COGS account",
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Expense account for supplies/consumables",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense_items",
                        to="accounting.account",
                        verbose_name="expense account",
                    ),
                ),
                (
                    "inventory_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Asset account for inventory value",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_items",
                        to="accounting.account",
                        verbose_name="inventory account",
                    ),
                ),
                (
                    "sat_product_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.satproductcode",
                        verbose_name="SAT Clave Producto",
                    ),
                ),
                (
                    "sat_unit_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.satunitcode",
                        verbose_name="SAT Clave Unidad",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.taxrate",
                        verbose_name="tax rate",
                    ),
                ),
            ],
            options={
                "verbose_name": "inventory item",
                "verbose_name_plural": "inventory items",
                "ordering": ["name"],
            },
        ),
    ]
