# Generated by Django 5.2.9 on 2025-12-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_add_inventory_item_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique identifier (e.g., 'medication', 'food')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "name_es",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="name (Spanish)"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "requires_refrigeration",
                    models.BooleanField(
                        default=False,
                        help_text="Items in this category need temperature-controlled storage",
                        verbose_name="requires refrigeration",
                    ),
                ),
                (
                    "requires_controlled_access",
                    models.BooleanField(
                        default=False,
                        help_text="Items require restricted access (e.g., controlled substances)",
                        verbose_name="requires controlled access",
                    ),
                ),
                (
                    "is_pharmaceutical",
                    models.BooleanField(
                        default=False,
                        help_text="Items are pharmaceuticals requiring special handling",
                        verbose_name="pharmaceutical",
                    ),
                ),
                (
                    "is_perishable",
                    models.BooleanField(
                        default=False,
                        help_text="Items have expiration dates that must be tracked",
                        verbose_name="perishable",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name for UI display",
                        max_length=50,
                        verbose_name="icon",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "inventory category",
                "verbose_name_plural": "inventory categories",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
