# Generated by Django 5.2.9 on 2025-12-24 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_es", models.CharField(blank=True, max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("service", "Service Page"),
                            ("location", "Location Page"),
                            ("campaign", "Campaign Page"),
                            ("seasonal", "Seasonal Page"),
                        ],
                        max_length=20,
                    ),
                ),
                ("headline", models.CharField(max_length=100)),
                ("headline_es", models.CharField(blank=True, max_length=100)),
                ("subheadline", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField()),
                ("content_es", models.TextField(blank=True)),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="landing/"),
                ),
                ("cta_text", models.CharField(default="Get Started", max_length=50)),
                ("cta_url", models.CharField(blank=True, max_length=200)),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("schema_markup", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("is_indexed", models.BooleanField(default=True)),
                ("view_count", models.IntegerField(default=0)),
                ("conversion_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Redirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_path", models.CharField(max_length=500, unique=True)),
                ("new_path", models.CharField(max_length=500)),
                (
                    "redirect_type",
                    models.IntegerField(
                        choices=[(301, "Permanent (301)"), (302, "Temporary (302)")],
                        default=301,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("hit_count", models.IntegerField(default=0)),
                ("last_hit", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["old_path"],
            },
        ),
        migrations.CreateModel(
            name="SEOMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="URL path like /services/",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=70)),
                ("title_es", models.CharField(blank=True, max_length=70)),
                ("description", models.CharField(max_length=160)),
                ("description_es", models.CharField(blank=True, max_length=160)),
                ("keywords", models.CharField(blank=True, max_length=200)),
                ("canonical_url", models.URLField(blank=True)),
                ("og_title", models.CharField(blank=True, max_length=100)),
                ("og_description", models.CharField(blank=True, max_length=200)),
                ("og_image", models.URLField(blank=True)),
                (
                    "twitter_card",
                    models.CharField(default="summary_large_image", max_length=20),
                ),
                ("twitter_title", models.CharField(blank=True, max_length=100)),
                ("twitter_description", models.CharField(blank=True, max_length=200)),
                ("schema_markup", models.JSONField(blank=True, default=dict)),
                ("robots", models.CharField(default="index, follow", max_length=50)),
                (
                    "priority",
                    models.DecimalField(decimal_places=1, default=0.5, max_digits=2),
                ),
                ("changefreq", models.CharField(default="weekly", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SEO Metadata",
                "verbose_name_plural": "SEO Metadata",
            },
        ),
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_es", models.CharField(blank=True, max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="seo.blogcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Blog Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_es", models.CharField(blank=True, max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        blank=True, help_text="Short summary for listings"
                    ),
                ),
                ("excerpt_es", models.TextField(blank=True)),
                ("content", models.TextField()),
                ("content_es", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="blog/"),
                ),
                ("featured_image_alt", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Under Review"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("meta_keywords", models.CharField(blank=True, max_length=200)),
                (
                    "og_title",
                    models.CharField(
                        blank=True, help_text="Open Graph title", max_length=100
                    ),
                ),
                ("og_description", models.CharField(blank=True, max_length=200)),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="blog/og/"),
                ),
                ("canonical_url", models.URLField(blank=True)),
                ("schema_markup", models.JSONField(blank=True, default=dict)),
                ("view_count", models.IntegerField(default=0)),
                ("reading_time_minutes", models.IntegerField(default=5)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="seo.blogcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentCalendarItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("blog", "Blog Post"),
                            ("social", "Social Media"),
                            ("email", "Email Campaign"),
                            ("landing", "Landing Page"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idea", "Idea"),
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("review", "Under Review"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                        ],
                        default="idea",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("target_keywords", models.JSONField(blank=True, default=list)),
                ("target_audience", models.CharField(blank=True, max_length=200)),
                ("planned_date", models.DateField(blank=True, null=True)),
                ("published_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_content",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blog_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="seo.blogpost",
                    ),
                ),
                (
                    "landing_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="seo.landingpage",
                    ),
                ),
            ],
            options={
                "ordering": ["planned_date", "-created_at"],
            },
        ),
    ]
