# Generated by Django 5.2.9 on 2025-12-26 02:50

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="featured_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.core.storage.blog_image_path
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="og_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.core.storage.og_image_path
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="hero_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.core.storage.landing_image_path
            ),
        ),
    ]
