"""
Workflow configuration for GIF animation recording.

Define the workflows to record for documentation.
"""

WORKFLOWS = {
    "login_flow": {
        "name": "Login Flow",
        "name_es": "Flujo de Inicio de Sesión",
        "role": "anonymous",  # No auth needed - this IS the login
        "steps": [
            {"action": "goto", "url": "/accounts/login/"},
            {"action": "wait", "selector": "#id_username"},
            {"action": "fill", "selector": "#id_username", "value": "demo@petfriendly.com"},
            {"action": "wait", "ms": 300},
            {"action": "fill", "selector": "#id_password", "value": "••••••••"},
            {"action": "wait", "ms": 500},
            {"action": "click", "selector": "button[type='submit']"},
            {"action": "wait", "ms": 1000},
        ],
        "output_gif": "login_flow.gif",
    },
    "add_pet_flow": {
        "name": "Add Pet Flow",
        "name_es": "Flujo de Agregar Mascota",
        "role": "customer",
        "steps": [
            {"action": "goto", "url": "/pets/add/"},
            {"action": "wait", "selector": "#id_name"},
            {"action": "fill", "selector": "#id_name", "value": "Max"},
            {"action": "wait", "ms": 300},
            {"action": "click", "selector": "#id_species"},
            {"action": "wait", "ms": 300},
            {"action": "select", "selector": "#id_species", "value": "dog"},
            {"action": "wait", "ms": 300},
            {"action": "fill", "selector": "#id_breed", "value": "Golden Retriever"},
            {"action": "wait", "ms": 500},
            {"action": "screenshot", "name": "pet_form_filled"},
        ],
        "output_gif": "add_pet_flow.gif",
    },
    "book_appointment_flow": {
        "name": "Book Appointment",
        "name_es": "Reservar Cita",
        "role": "customer",
        "steps": [
            {"action": "goto", "url": "/appointments/book/"},
            {"action": "wait", "selector": "#booking-form"},
            {"action": "click", "selector": "#id_service"},
            {"action": "wait", "ms": 300},
            {"action": "click", "selector": "#id_pet"},
            {"action": "wait", "ms": 300},
            {"action": "click", "selector": "#id_date"},
            {"action": "wait", "ms": 500},
            {"action": "screenshot", "name": "appointment_form"},
        ],
        "output_gif": "book_appointment.gif",
    },
    "browse_store_flow": {
        "name": "Browse Store",
        "name_es": "Explorar Tienda",
        "role": "customer",
        "steps": [
            {"action": "goto", "url": "/store/"},
            {"action": "wait", "selector": ".grid"},
            {"action": "wait", "ms": 500},
            {"action": "scroll", "y": 300},
            {"action": "wait", "ms": 500},
            {"action": "scroll", "y": 0},
            {"action": "wait", "ms": 300},
            {"action": "screenshot", "name": "store_browse"},
        ],
        "output_gif": "browse_store.gif",
    },
    "view_cart_flow": {
        "name": "View Cart",
        "name_es": "Ver Carrito",
        "role": "customer",
        "steps": [
            {"action": "goto", "url": "/store/cart/"},
            {"action": "wait", "selector": ".max-w-7xl"},
            {"action": "wait", "ms": 500},
            {"action": "screenshot", "name": "cart_view"},
        ],
        "output_gif": "view_cart.gif",
    },
    "loyalty_dashboard_flow": {
        "name": "View Loyalty Dashboard",
        "name_es": "Ver Panel de Lealtad",
        "role": "customer",
        "steps": [
            {"action": "goto", "url": "/loyalty/"},
            {"action": "wait", "selector": ".max-w-7xl"},
            {"action": "wait", "ms": 500},
            {"action": "scroll", "y": 200},
            {"action": "wait", "ms": 500},
            {"action": "goto", "url": "/loyalty/rewards/"},
            {"action": "wait", "selector": ".grid"},
            {"action": "wait", "ms": 500},
            {"action": "screenshot", "name": "loyalty_rewards"},
        ],
        "output_gif": "loyalty_dashboard.gif",
    },
    "pet_dashboard_flow": {
        "name": "Pet Dashboard Navigation",
        "name_es": "Navegación Panel de Mascotas",
        "role": "customer",
        "steps": [
            {"action": "goto", "url": "/pets/"},
            {"action": "wait", "selector": ".max-w-7xl"},
            {"action": "wait", "ms": 500},
            {"action": "scroll", "y": 200},
            {"action": "wait", "ms": 500},
            {"action": "scroll", "y": 0},
            {"action": "wait", "ms": 300},
            {"action": "screenshot", "name": "pet_dashboard"},
        ],
        "output_gif": "pet_dashboard.gif",
    },
    "staff_practice_flow": {
        "name": "Practice Management",
        "name_es": "Gestión de Práctica",
        "role": "staff",
        "steps": [
            {"action": "goto", "url": "/practice/"},
            {"action": "wait", "selector": ".max-w-7xl"},
            {"action": "wait", "ms": 500},
            {"action": "scroll", "y": 200},
            {"action": "wait", "ms": 500},
            {"action": "goto", "url": "/practice/staff/"},
            {"action": "wait", "selector": ".max-w-7xl"},
            {"action": "wait", "ms": 500},
            {"action": "screenshot", "name": "staff_list"},
        ],
        "output_gif": "practice_management.gif",
    },
    "staff_inventory_flow": {
        "name": "Inventory Overview",
        "name_es": "Vista de Inventario",
        "role": "staff",
        "steps": [
            {"action": "goto", "url": "/inventory/"},
            {"action": "wait", "selector": ".max-w-7xl"},
            {"action": "wait", "ms": 500},
            {"action": "scroll", "y": 200},
            {"action": "wait", "ms": 500},
            {"action": "goto", "url": "/inventory/stock/"},
            {"action": "wait", "selector": ".max-w-7xl"},
            {"action": "wait", "ms": 500},
            {"action": "screenshot", "name": "stock_levels"},
        ],
        "output_gif": "inventory_overview.gif",
    },
}
