# Generated by Django 5.2.9 on 2025-12-27 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_add_shift_model"),
        ("practice", "0005_add_qualified_providers_consumables"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeentry",
            name="task",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional task this time entry is associated with",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_entries",
                to="practice.task",
                verbose_name="task",
            ),
        ),
    ]
