# Generated by Django 5.2.9 on 2025-12-27 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_migrate_practice_data"),
        ("parties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ["user__last_name", "user__first_name"],
                "verbose_name": "employee (deprecated)",
                "verbose_name_plural": "employees (deprecated)",
            },
        ),
        # Add person field FIRST (before unique_together can reference it)
        migrations.AddField(
            model_name="shift",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shifts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="person",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shifts",
                to="parties.organization",
                verbose_name="organization",
            ),
        ),
        # Now we can set unique_together with person
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together={("person", "date", "start_time")},
        ),
        migrations.RemoveField(
            model_name="timeentry",
            name="employee",
        ),
        migrations.AddField(
            model_name="timeentry",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Which organization this time is for (if multi-org)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_entries",
                to="parties.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_entries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="person",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_departments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="department manager",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="old_direct_reports",
                to="hr.employee",
                verbose_name="manager",
            ),
        ),
        migrations.CreateModel(
            name="EmploymentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="employee/contractor ID",
                    ),
                ),
                (
                    "work_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="work email"
                    ),
                ),
                (
                    "work_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="work phone"
                    ),
                ),
                (
                    "rfc",
                    models.CharField(
                        blank=True,
                        help_text="Tax ID (Mexico)",
                        max_length=13,
                        verbose_name="RFC",
                    ),
                ),
                (
                    "curp",
                    models.CharField(
                        blank=True,
                        help_text="Personal ID (Mexico)",
                        max_length=18,
                        verbose_name="CURP",
                    ),
                ),
                (
                    "imss_number",
                    models.CharField(
                        blank=True,
                        help_text="Social security number (Mexico)",
                        max_length=20,
                        verbose_name="IMSS number",
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="salary",
                    ),
                ),
                (
                    "pay_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Biweekly"),
                            ("semimonthly", "Semi-monthly"),
                            ("monthly", "Monthly"),
                        ],
                        default="biweekly",
                        max_length=20,
                        verbose_name="pay frequency",
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("per_job", "Per Job"),
                            ("fixed_monthly", "Fixed Monthly"),
                        ],
                        max_length=20,
                        verbose_name="rate type",
                    ),
                ),
                (
                    "rate_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="rate amount",
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("immediate", "Immediate"),
                            ("net_7", "Net 7"),
                            ("net_15", "Net 15"),
                            ("net_30", "Net 30"),
                            ("on_completion", "On Completion"),
                        ],
                        max_length=30,
                        verbose_name="payment terms",
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="emergency contact name",
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="emergency contact phone",
                    ),
                ),
                (
                    "contract_documents",
                    models.JSONField(
                        blank=True, default=list, verbose_name="contract documents"
                    ),
                ),
                (
                    "sops",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Standard Operating Procedures",
                        verbose_name="SOPs",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employment_details",
                        to="hr.department",
                        verbose_name="department",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="manager",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employment_details",
                        to="hr.position",
                        verbose_name="position",
                    ),
                ),
                (
                    "relationship",
                    models.OneToOneField(
                        help_text="The employment relationship this extends",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employment_details",
                        to="parties.partyrelationship",
                        verbose_name="relationship",
                    ),
                ),
            ],
            options={
                "verbose_name": "employment details",
                "verbose_name_plural": "employment details",
            },
        ),
        migrations.RemoveField(
            model_name="shift",
            name="employee",
        ),
    ]
