# Generated by Django 5.2.9 on 2025-12-23 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0003_vaccination_reminder_sent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="country code"
                    ),
                ),
                (
                    "country_name",
                    models.CharField(max_length=100, verbose_name="country name"),
                ),
                (
                    "requirements",
                    models.JSONField(
                        default=dict,
                        help_text="JSON object with requirement details",
                        verbose_name="requirements",
                    ),
                ),
                (
                    "certificate_validity_days",
                    models.IntegerField(
                        default=10,
                        help_text="How many days the health certificate is valid",
                        verbose_name="certificate validity (days)",
                    ),
                ),
                (
                    "quarantine_required",
                    models.BooleanField(
                        default=False, verbose_name="quarantine required"
                    ),
                ),
                (
                    "quarantine_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="quarantine days"
                    ),
                ),
                (
                    "airline_requirements",
                    models.TextField(blank=True, verbose_name="airline requirements"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="last updated"),
                ),
            ],
            options={
                "verbose_name": "travel destination",
                "verbose_name_plural": "travel destinations",
                "ordering": ["country_name"],
            },
        ),
        migrations.CreateModel(
            name="HealthCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("travel_date", models.DateField(verbose_name="travel date")),
                (
                    "issue_date",
                    models.DateField(blank=True, null=True, verbose_name="issue date"),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="expiry date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_review", "In Review"),
                            ("issued", "Issued"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="certificate number"
                    ),
                ),
                (
                    "pdf_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="travel_certificates/",
                        verbose_name="PDF document",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates_issued",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="issued by",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_certificates",
                        to="pets.pet",
                        verbose_name="pet",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificates",
                        to="travel.traveldestination",
                        verbose_name="destination",
                    ),
                ),
            ],
            options={
                "verbose_name": "health certificate",
                "verbose_name_plural": "health certificates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CertificateRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requirement_type",
                    models.CharField(max_length=50, verbose_name="requirement type"),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="verified"),
                ),
                (
                    "verified_at",
                    models.DateField(blank=True, null=True, verbose_name="verified at"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requirements_verified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="verified by",
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="travel.healthcertificate",
                        verbose_name="certificate",
                    ),
                ),
            ],
            options={
                "verbose_name": "certificate requirement",
                "verbose_name_plural": "certificate requirements",
                "ordering": ["requirement_type"],
            },
        ),
        migrations.CreateModel(
            name="TravelPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_date", models.DateField(verbose_name="departure date")),
                (
                    "return_date",
                    models.DateField(blank=True, null=True, verbose_name="return date"),
                ),
                (
                    "airline",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="airline"
                    ),
                ),
                (
                    "flight_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="flight number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("documents_pending", "Documents Pending"),
                            ("ready", "Ready to Travel"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planning",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="travel_plans",
                        to="travel.healthcertificate",
                        verbose_name="health certificate",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="travel_plans",
                        to="travel.traveldestination",
                        verbose_name="destination",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_plans",
                        to="pets.pet",
                        verbose_name="pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "travel plan",
                "verbose_name_plural": "travel plans",
                "ordering": ["-departure_date"],
            },
        ),
    ]
