# Generated by Django 5.2.9 on 2025-12-26 02:50

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthcertificate",
            name="pdf_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.core.storage.travel_document_path,
                verbose_name="PDF document",
            ),
        ),
    ]
