"""Multilingual models for AI-powered translation system."""
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.translation import gettext_lazy as _


class Language(models.Model):
    """Language configuration for the multilingual system."""

    code = models.CharField(
        _('language code'),
        max_length=5,
        unique=True,
        help_text=_('ISO 639-1 language code (e.g., es, en, de)')
    )
    name = models.CharField(
        _('name'),
        max_length=50,
        help_text=_('Language name in English')
    )
    native_name = models.CharField(
        _('native name'),
        max_length=50,
        help_text=_('Language name in its own language')
    )
    is_core = models.BooleanField(
        _('core language'),
        default=False,
        help_text=_('Core languages have pre-translated content')
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_('Inactive languages are not shown to users')
    )
    flag_emoji = models.CharField(
        _('flag emoji'),
        max_length=10,
        blank=True,
        default='',
        help_text=_('Flag emoji for visual display')
    )

    class Meta:
        verbose_name = _('language')
        verbose_name_plural = _('languages')
        ordering = ['-is_core', 'name']

    def __str__(self):
        return f'{self.native_name} ({self.code})'


class TranslatedContent(models.Model):
    """Stores translations for any model field using GenericForeignKey."""

    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE,
        verbose_name=_('content type')
    )
    object_id = models.PositiveIntegerField(_('object ID'))
    content_object = GenericForeignKey('content_type', 'object_id')

    language = models.ForeignKey(
        Language,
        on_delete=models.CASCADE,
        verbose_name=_('language')
    )
    field_name = models.CharField(
        _('field name'),
        max_length=100,
        help_text=_('Name of the model field being translated')
    )
    translation = models.TextField(
        _('translation'),
        help_text=_('Translated content')
    )
    is_ai_generated = models.BooleanField(
        _('AI generated'),
        default=False,
        help_text=_('True if translation was generated by AI')
    )
    verified_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='verified_translations',
        verbose_name=_('verified by')
    )
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('updated at'), auto_now=True)

    class Meta:
        verbose_name = _('translated content')
        verbose_name_plural = _('translated content')
        unique_together = ['content_type', 'object_id', 'language', 'field_name']
        indexes = [
            models.Index(fields=['content_type', 'object_id']),
            models.Index(fields=['language', 'field_name']),
        ]

    def __str__(self):
        return f'{self.field_name} ({self.language.code})'
