# Generated by Django 5.2.9 on 2025-12-23 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnownBug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("bug_id", models.CharField(max_length=10, unique=True)),
                (
                    "fingerprint",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("github_issue_number", models.IntegerField(blank=True, null=True)),
                ("github_issue_url", models.URLField(blank=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("wontfix", "Won't Fix"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("occurrence_count", models.IntegerField(default=1)),
                ("last_occurrence", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Known Bug",
                "verbose_name_plural": "Known Bugs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                ("error_type", models.CharField(max_length=50)),
                ("status_code", models.IntegerField()),
                ("url_pattern", models.CharField(max_length=500)),
                ("full_url", models.URLField(max_length=2000)),
                ("method", models.CharField(max_length=10)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("request_data", models.JSONField(blank=True, default=dict)),
                ("exception_type", models.CharField(blank=True, max_length=200)),
                ("exception_message", models.TextField(blank=True)),
                ("traceback", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="error_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Error Log",
                "verbose_name_plural": "Error Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["fingerprint", "created_at"],
                        name="error_track_fingerp_2a01d7_idx",
                    ),
                    models.Index(
                        fields=["status_code", "created_at"],
                        name="error_track_status__442b88_idx",
                    ),
                ],
            },
        ),
    ]
