# Generated by Django 5.2.9 on 2025-12-26 02:50

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.core.storage.review_photo_path
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="author_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.core.storage.testimonial_photo_path,
            ),
        ),
    ]
