# Generated by Django 5.2.9 on 2025-12-27 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_reminder_fields"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Clinic location for this appointment",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="locations.location",
                verbose_name="location",
            ),
        ),
    ]
