# Generated by Django 5.2.9 on 2025-12-27 14:32

from django.db import migrations, models
import django.db.models.deletion


def set_default_location(apps, schema_editor):
    """Set default location for appointments without one.

    Uses the first active location (Clinica Principal, ID 1).
    """
    Appointment = apps.get_model('appointments', 'Appointment')
    Location = apps.get_model('locations', 'Location')

    # Get the default location (first active one)
    default_location = Location.objects.filter(is_active=True).order_by('id').first()

    if default_location:
        # Update all appointments without a location
        count = Appointment.objects.filter(location__isnull=True).update(
            location=default_location
        )
        if count > 0:
            print(f"Updated {count} appointments to use location: {default_location.name}")
    else:
        print("WARNING: No active location found. Migration may fail if there are appointments without location.")


def reverse_set_location(apps, schema_editor):
    """No-op reverse - we can't know which were null before."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_add_location_to_appointment'),
        ('locations', '0001_initial'),
    ]

    operations = [
        # Step 1: Set default location for existing null records
        migrations.RunPython(set_default_location, reverse_set_location),

        # Step 2: Make the field required (remove null=True, blank=True)
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(
                help_text='Clinic location for this appointment',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='appointments',
                to='locations.location',
                verbose_name='location',
            ),
        ),
    ]
