# Generated by Django 5.2.9 on 2025-12-22 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 639-1 language code (e.g., es, en, de)",
                        max_length=5,
                        unique=True,
                        verbose_name="language code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Language name in English",
                        max_length=50,
                        verbose_name="name",
                    ),
                ),
                (
                    "native_name",
                    models.CharField(
                        help_text="Language name in its own language",
                        max_length=50,
                        verbose_name="native name",
                    ),
                ),
                (
                    "is_core",
                    models.BooleanField(
                        default=False,
                        help_text="Core languages have pre-translated content",
                        verbose_name="core language",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive languages are not shown to users",
                        verbose_name="active",
                    ),
                ),
                (
                    "flag_emoji",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Flag emoji for visual display",
                        max_length=10,
                        verbose_name="flag emoji",
                    ),
                ),
            ],
            options={
                "verbose_name": "language",
                "verbose_name_plural": "languages",
                "ordering": ["-is_core", "name"],
            },
        ),
        migrations.CreateModel(
            name="TranslatedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="object ID")),
                (
                    "field_name",
                    models.CharField(
                        help_text="Name of the model field being translated",
                        max_length=100,
                        verbose_name="field name",
                    ),
                ),
                (
                    "translation",
                    models.TextField(
                        help_text="Translated content", verbose_name="translation"
                    ),
                ),
                (
                    "is_ai_generated",
                    models.BooleanField(
                        default=False,
                        help_text="True if translation was generated by AI",
                        verbose_name="AI generated",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="multilingual.language",
                        verbose_name="language",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_translations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="verified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "translated content",
                "verbose_name_plural": "translated content",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="multilingua_content_a478a8_idx",
                    ),
                    models.Index(
                        fields=["language", "field_name"],
                        name="multilingua_languag_98eeea_idx",
                    ),
                ],
                "unique_together": {
                    ("content_type", "object_id", "language", "field_name")
                },
            },
        ),
    ]
