# Generated by Django 5.2.9 on 2025-12-23 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("dog", "Dog"),
                            ("cat", "Cat"),
                            ("bird", "Bird"),
                            ("rabbit", "Rabbit"),
                            ("hamster", "Hamster"),
                            ("guinea_pig", "Guinea Pig"),
                            ("reptile", "Reptile"),
                            ("other", "Other"),
                        ],
                        default="dog",
                        max_length=20,
                        verbose_name="species",
                    ),
                ),
                (
                    "breed",
                    models.CharField(blank=True, max_length=100, verbose_name="breed"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                        verbose_name="gender",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth"
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="weight (kg)",
                    ),
                ),
                (
                    "microchip_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="microchip ID"
                    ),
                ),
                (
                    "is_neutered",
                    models.BooleanField(default=False, verbose_name="neutered/spayed"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="pets/", verbose_name="photo"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "pet",
                "verbose_name_plural": "pets",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="medication name"),
                ),
                ("dosage", models.CharField(max_length=100, verbose_name="dosage")),
                (
                    "frequency",
                    models.CharField(max_length=100, verbose_name="frequency"),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="end date"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prescribing_vet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="prescribing veterinarian",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="pets.pet",
                        verbose_name="pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "medication",
                "verbose_name_plural": "medications",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="MedicalCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="condition name"),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("allergy", "Allergy"),
                            ("chronic", "Chronic Condition"),
                            ("injury", "Injury"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "diagnosed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="diagnosed date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="pets.pet",
                        verbose_name="pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "medical condition",
                "verbose_name_plural": "medical conditions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vaccination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vaccine_name",
                    models.CharField(max_length=200, verbose_name="vaccine name"),
                ),
                (
                    "date_administered",
                    models.DateField(verbose_name="date administered"),
                ),
                (
                    "next_due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="next due date"
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="batch number"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "administered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vaccinations_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="administered by",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccinations",
                        to="pets.pet",
                        verbose_name="pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "vaccination",
                "verbose_name_plural": "vaccinations",
                "ordering": ["-date_administered"],
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="visit date")),
                (
                    "reason",
                    models.CharField(max_length=500, verbose_name="reason for visit"),
                ),
                ("diagnosis", models.TextField(blank=True, verbose_name="diagnosis")),
                ("treatment", models.TextField(blank=True, verbose_name="treatment")),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="weight at visit (kg)",
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="follow-up date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="pets.pet",
                        verbose_name="pet",
                    ),
                ),
                (
                    "veterinarian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visits_conducted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="veterinarian",
                    ),
                ),
            ],
            options={
                "verbose_name": "visit",
                "verbose_name_plural": "visits",
                "ordering": ["-date"],
            },
        ),
    ]
