# Generated by Django 5.2.9 on 2025-12-23 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_pet_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(verbose_name="note")),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("observation", "Observation"),
                            ("treatment", "Treatment Note"),
                            ("followup", "Follow-up"),
                            ("lab", "Lab Results"),
                            ("other", "Other"),
                        ],
                        default="observation",
                        max_length=20,
                        verbose_name="note type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_notes_authored",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_notes",
                        to="pets.pet",
                        verbose_name="pet",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_notes",
                        to="pets.visit",
                        verbose_name="related visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "clinical note",
                "verbose_name_plural": "clinical notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PetDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("lab_result", "Lab Result"),
                            ("xray", "X-Ray"),
                            ("photo", "Photo"),
                            ("certificate", "Certificate"),
                            ("prescription", "Prescription"),
                            ("referral", "Referral"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="document type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="pet_documents/",
                        verbose_name="file",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "visible_to_owner",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the pet owner can see this document",
                        verbose_name="visible to owner",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="pets.pet",
                        verbose_name="pet",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pet_documents_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "pet document",
                "verbose_name_plural": "pet documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeightRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="weight (kg)"
                    ),
                ),
                (
                    "recorded_date",
                    models.DateField(auto_now_add=True, verbose_name="recorded date"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_records",
                        to="pets.pet",
                        verbose_name="pet",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weight_records_recorded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recorded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "weight record",
                "verbose_name_plural": "weight records",
                "ordering": ["-recorded_date"],
            },
        ),
    ]
