# Generated by Django 5.2.9 on 2025-12-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0002_medical_records"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccination",
            name="reminder_sent",
            field=models.BooleanField(default=False, verbose_name="reminder sent"),
        ),
        migrations.AddField(
            model_name="vaccination",
            name="reminder_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="reminder sent at"
            ),
        ),
    ]
