# Generated by Django 5.2.9 on 2025-12-24 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0003_vaccination_reminder_sent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="prescribing_vet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pet_medications_prescribed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="prescribing veterinarian",
            ),
        ),
    ]
