# Generated by Django 5.2.9 on 2025-12-26 02:50

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0004_alter_medication_prescribing_vet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.core.storage.pet_photo_path,
                verbose_name="photo",
            ),
        ),
        migrations.AlterField(
            model_name="petdocument",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.core.storage.pet_document_path,
                verbose_name="file",
            ),
        ),
    ]
