# Generated by Django 5.2.9 on 2025-12-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0005_alter_pet_photo_alter_petdocument_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="deceased_date",
            field=models.DateField(
                blank=True,
                help_text="If the pet has passed away",
                null=True,
                verbose_name="date passed away",
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Hidden from active pet list but preserved for records",
                verbose_name="archived",
            ),
        ),
    ]
