# Generated by Django 5.2.9 on 2025-12-27 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0001_initial"),
        ("pets", "0006_add_archive_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="owner_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Household/family group that owns this pet",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_pets",
                to="parties.group",
                verbose_name="owner (group)",
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="owner_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this pet (zoo, school, rescue, etc.)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_pets",
                to="parties.organization",
                verbose_name="owner (organization)",
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="owner_person",
            field=models.ForeignKey(
                blank=True,
                help_text="Individual person who owns this pet",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_pets",
                to="parties.person",
                verbose_name="owner (person)",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="DEPRECATED: Use owner_person instead",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner (deprecated)",
            ),
        ),
        migrations.CreateModel(
            name="PetResponsibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "responsibility_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Responsible"),
                            ("secondary", "Secondary/Backup"),
                            ("caretaker", "Caretaker"),
                            ("emergency", "Emergency Contact"),
                            ("veterinary", "Veterinary Contact"),
                            ("other", "Other"),
                        ],
                        default="primary",
                        max_length=20,
                        verbose_name="responsibility type",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="start date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="end date"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pet_responsibilities",
                        to="parties.person",
                        verbose_name="person",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsibilities",
                        to="pets.pet",
                        verbose_name="pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "pet responsibility",
                "verbose_name_plural": "pet responsibilities",
                "ordering": ["responsibility_type", "person__last_name"],
                "unique_together": {("pet", "person", "responsibility_type")},
            },
        ),
    ]
