# Generated by Django 5.2.9 on 2025-12-23 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_appointments",
                    models.BooleanField(
                        default=True, verbose_name="email appointment reminders"
                    ),
                ),
                (
                    "email_vaccinations",
                    models.BooleanField(
                        default=True, verbose_name="email vaccination reminders"
                    ),
                ),
                (
                    "email_promotions",
                    models.BooleanField(default=False, verbose_name="email promotions"),
                ),
                (
                    "email_system",
                    models.BooleanField(
                        default=True, verbose_name="email system notifications"
                    ),
                ),
                (
                    "appointment_reminder_hours",
                    models.IntegerField(
                        default=24, verbose_name="appointment reminder hours before"
                    ),
                ),
                (
                    "vaccination_reminder_days",
                    models.IntegerField(
                        default=14, verbose_name="vaccination reminder days before"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification preference",
                "verbose_name_plural": "notification preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("appointment_reminder", "Appointment Reminder"),
                            ("appointment_confirmed", "Appointment Confirmed"),
                            ("appointment_cancelled", "Appointment Cancelled"),
                            ("vaccination_reminder", "Vaccination Reminder"),
                            ("vaccination_overdue", "Vaccination Overdue"),
                            ("general", "General"),
                            ("promotion", "Promotion"),
                            ("system", "System"),
                        ],
                        default="general",
                        max_length=30,
                        verbose_name="type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("message", models.TextField(verbose_name="message")),
                (
                    "related_pet_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="related pet"
                    ),
                ),
                (
                    "related_appointment_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="related appointment"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="read")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="read at"),
                ),
                (
                    "email_sent",
                    models.BooleanField(default=False, verbose_name="email sent"),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="email sent at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_427e4b_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="notificatio_user_id_c62b26_idx",
                    ),
                ],
            },
        ),
    ]
